import type { Product } from './products'

// Catalogue cordage anonymisé. Ne contient aucune source fournisseur.
// Photos locales groupées par SKU dans public/catalogue/rope-series.
export const ROPE_PRODUCTS: Product[] = [
  {
    id: 'rope-rop-001',
    sku: 'ROP-001',
    category: 'bench',
    name: 'Salon de terrasse cordage CANNES - cordage ajouré blanc crème / avoine / gris clair',
    description:
      'Salon de terrasse cordage CANNES - cordage ajouré blanc crème / avoine / gris clair pour zone lounge, piscine, rooftop, camping, hôtel et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 180x78x78 cm, poids 24 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 180,
      w: 78,
      h: 78,
    },
    cbmPerUnit: 0.45,
    weightKg: 24,
    moqUnits: 20,
    basePriceHt: 449,
    retailPriceRef: 786,
    ecoContribution: 1.2,
    mainImageUrl: '/catalogue/rope-series/ROP-001-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-001-02.webp',
      '/catalogue/rope-series/ROP-001-03.webp',
      '/catalogue/rope-series/ROP-001-04.webp',
      '/catalogue/rope-series/ROP-001-05.webp',
      '/catalogue/rope-series/ROP-001-06.webp',
      '/catalogue/rope-series/ROP-001-07.webp',
      '/catalogue/rope-series/ROP-001-08.webp',
      '/catalogue/rope-series/ROP-001-09.webp',
      '/catalogue/rope-series/ROP-001-10.webp',
    ],
    variants: [
      {
        id: 'rop-001-design-principal',
        name: 'cordage ajouré blanc crème / avoine / gris clair / blanc',
        imageUrl: '/catalogue/rope-series/ROP-001-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-001-02.webp',
          '/catalogue/rope-series/ROP-001-03.webp',
          '/catalogue/rope-series/ROP-001-04.webp',
          '/catalogue/rope-series/ROP-001-05.webp',
          '/catalogue/rope-series/ROP-001-06.webp',
          '/catalogue/rope-series/ROP-001-07.webp',
          '/catalogue/rope-series/ROP-001-08.webp',
          '/catalogue/rope-series/ROP-001-09.webp',
          '/catalogue/rope-series/ROP-001-10.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Salon cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage ajouré',
      'Coloris blanc crème / avoine / gris clair / blanc',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-002',
    sku: 'ROP-002',
    category: 'armchair',
    name: 'Fauteuil de terrasse NICE - tressage blanc crème / blanc',
    description:
      'Fauteuil de terrasse NICE - tressage blanc crème / blanc pour terrasse de restaurant, café, hôtel, rooftop et espace CHR premium. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 62x60x82 cm, poids 6.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 62,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 6.2,
    moqUnits: 50,
    basePriceHt: 129,
    retailPriceRef: 226,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-002-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-002-02.webp',
      '/catalogue/rope-series/ROP-002-03.webp',
      '/catalogue/rope-series/ROP-002-04.webp',
      '/catalogue/rope-series/ROP-002-05.webp',
      '/catalogue/rope-series/ROP-002-06.webp',
      '/catalogue/rope-series/ROP-002-07.webp',
      '/catalogue/rope-series/ROP-002-08.webp',
      '/catalogue/rope-series/ROP-002-09.webp',
      '/catalogue/rope-series/ROP-002-10.webp',
      '/catalogue/rope-series/ROP-002-11.webp',
    ],
    variants: [
      {
        id: 'rop-002-design-principal',
        name: 'cordage tressé blanc crème / blanc',
        imageUrl: '/catalogue/rope-series/ROP-002-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-002-02.webp',
          '/catalogue/rope-series/ROP-002-03.webp',
          '/catalogue/rope-series/ROP-002-04.webp',
          '/catalogue/rope-series/ROP-002-05.webp',
          '/catalogue/rope-series/ROP-002-06.webp',
          '/catalogue/rope-series/ROP-002-07.webp',
          '/catalogue/rope-series/ROP-002-08.webp',
          '/catalogue/rope-series/ROP-002-09.webp',
          '/catalogue/rope-series/ROP-002-10.webp',
          '/catalogue/rope-series/ROP-002-11.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Fauteuil cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage tressé',
      'Coloris blanc crème / blanc',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-003',
    sku: 'ROP-003',
    category: 'armchair',
    name: 'Fauteuil de terrasse ANTIBES - cordage ajouré blanc crème / avoine / gris clair',
    description:
      'Fauteuil de terrasse ANTIBES - cordage ajouré blanc crème / avoine / gris clair pour terrasse de restaurant, café, hôtel, rooftop et espace CHR premium. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 62x60x82 cm, poids 6.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 62,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 6.2,
    moqUnits: 50,
    basePriceHt: 129,
    retailPriceRef: 226,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-003-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-003-02.webp',
      '/catalogue/rope-series/ROP-003-03.webp',
      '/catalogue/rope-series/ROP-003-04.webp',
      '/catalogue/rope-series/ROP-003-05.webp',
      '/catalogue/rope-series/ROP-003-06.webp',
      '/catalogue/rope-series/ROP-003-07.webp',
      '/catalogue/rope-series/ROP-003-08.webp',
      '/catalogue/rope-series/ROP-003-09.webp',
    ],
    variants: [
      {
        id: 'rop-003-design-principal',
        name: 'cordage ajouré blanc crème / avoine / gris clair / blanc',
        imageUrl: '/catalogue/rope-series/ROP-003-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-003-02.webp',
          '/catalogue/rope-series/ROP-003-03.webp',
          '/catalogue/rope-series/ROP-003-04.webp',
          '/catalogue/rope-series/ROP-003-05.webp',
          '/catalogue/rope-series/ROP-003-06.webp',
          '/catalogue/rope-series/ROP-003-07.webp',
          '/catalogue/rope-series/ROP-003-08.webp',
          '/catalogue/rope-series/ROP-003-09.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Fauteuil cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage ajouré',
      'Coloris blanc crème / avoine / gris clair / blanc',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-004',
    sku: 'ROP-004',
    category: 'table',
    name: 'Table de terrasse MENTON - cordage outdoor',
    description:
      'Table de terrasse MENTON - cordage outdoor pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 160x90x74 cm, poids 18 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 160,
      w: 90,
      h: 74,
    },
    cbmPerUnit: 0.18,
    weightKg: 18,
    moqUnits: 20,
    basePriceHt: 229,
    retailPriceRef: 401,
    ecoContribution: 0.8,
    mainImageUrl: '/catalogue/rope-series/ROP-004-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-004-02.webp',
      '/catalogue/rope-series/ROP-004-03.webp',
      '/catalogue/rope-series/ROP-004-04.webp',
      '/catalogue/rope-series/ROP-004-05.webp',
      '/catalogue/rope-series/ROP-004-06.webp',
      '/catalogue/rope-series/ROP-004-07.webp',
      '/catalogue/rope-series/ROP-004-08.webp',
      '/catalogue/rope-series/ROP-004-09.webp',
      '/catalogue/rope-series/ROP-004-10.webp',
      '/catalogue/rope-series/ROP-004-11.webp',
    ],
    variants: [
      {
        id: 'rop-004-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-004-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-004-02.webp',
          '/catalogue/rope-series/ROP-004-03.webp',
          '/catalogue/rope-series/ROP-004-04.webp',
          '/catalogue/rope-series/ROP-004-05.webp',
          '/catalogue/rope-series/ROP-004-06.webp',
          '/catalogue/rope-series/ROP-004-07.webp',
          '/catalogue/rope-series/ROP-004-08.webp',
          '/catalogue/rope-series/ROP-004-09.webp',
          '/catalogue/rope-series/ROP-004-10.webp',
          '/catalogue/rope-series/ROP-004-11.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Ensemble repas cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-005',
    sku: 'ROP-005',
    category: 'armchair',
    name: 'Fauteuil de terrasse CASSIS - tressage',
    description:
      'Fauteuil de terrasse CASSIS - tressage pour terrasse de restaurant, café, hôtel, rooftop et espace CHR premium. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 62x60x82 cm, poids 6.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 62,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 6.2,
    moqUnits: 50,
    basePriceHt: 129,
    retailPriceRef: 226,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-005-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-005-02.webp',
      '/catalogue/rope-series/ROP-005-03.webp',
      '/catalogue/rope-series/ROP-005-04.webp',
      '/catalogue/rope-series/ROP-005-05.webp',
      '/catalogue/rope-series/ROP-005-06.webp',
      '/catalogue/rope-series/ROP-005-07.webp',
      '/catalogue/rope-series/ROP-005-08.webp',
      '/catalogue/rope-series/ROP-005-09.webp',
    ],
    variants: [
      {
        id: 'rop-005-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-005-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-005-02.webp',
          '/catalogue/rope-series/ROP-005-03.webp',
          '/catalogue/rope-series/ROP-005-04.webp',
          '/catalogue/rope-series/ROP-005-05.webp',
          '/catalogue/rope-series/ROP-005-06.webp',
          '/catalogue/rope-series/ROP-005-07.webp',
          '/catalogue/rope-series/ROP-005-08.webp',
          '/catalogue/rope-series/ROP-005-09.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Fauteuil cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage tressé',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-006',
    sku: 'ROP-006',
    category: 'armchair',
    name: 'Fauteuil de terrasse BIARRITZ - cordage outdoor',
    description:
      'Fauteuil de terrasse BIARRITZ - cordage outdoor pour terrasse de restaurant, café, hôtel, rooftop et espace CHR premium. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 62x60x82 cm, poids 6.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 62,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 6.2,
    moqUnits: 50,
    basePriceHt: 129,
    retailPriceRef: 226,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-006-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-006-02.webp',
      '/catalogue/rope-series/ROP-006-03.webp',
      '/catalogue/rope-series/ROP-006-04.webp',
      '/catalogue/rope-series/ROP-006-05.webp',
      '/catalogue/rope-series/ROP-006-06.webp',
    ],
    variants: [
      {
        id: 'rop-006-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-006-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-006-02.webp',
          '/catalogue/rope-series/ROP-006-03.webp',
          '/catalogue/rope-series/ROP-006-04.webp',
          '/catalogue/rope-series/ROP-006-05.webp',
          '/catalogue/rope-series/ROP-006-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Fauteuil cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-007',
    sku: 'ROP-007',
    category: 'armchair',
    name: 'Fauteuil de terrasse DEAUVILLE - tressage rouge',
    description:
      'Fauteuil de terrasse DEAUVILLE - tressage rouge pour terrasse de restaurant, café, hôtel, rooftop et espace CHR premium. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 62x60x82 cm, poids 6.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 62,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 6.2,
    moqUnits: 50,
    basePriceHt: 129,
    retailPriceRef: 226,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-007-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-007-02.webp',
      '/catalogue/rope-series/ROP-007-03.webp',
      '/catalogue/rope-series/ROP-007-04.webp',
      '/catalogue/rope-series/ROP-007-05.webp',
      '/catalogue/rope-series/ROP-007-06.webp',
    ],
    variants: [
      {
        id: 'rop-007-design-principal',
        name: 'tressage cordage rouge',
        imageUrl: '/catalogue/rope-series/ROP-007-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-007-02.webp',
          '/catalogue/rope-series/ROP-007-03.webp',
          '/catalogue/rope-series/ROP-007-04.webp',
          '/catalogue/rope-series/ROP-007-05.webp',
          '/catalogue/rope-series/ROP-007-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Fauteuil cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif tressage cordage',
      'Coloris rouge',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-008',
    sku: 'ROP-008',
    category: 'chair',
    name: 'Chaise de terrasse HONFLEUR - tressage rouge',
    description:
      'Chaise de terrasse HONFLEUR - tressage rouge pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-008-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-008-02.webp',
      '/catalogue/rope-series/ROP-008-03.webp',
      '/catalogue/rope-series/ROP-008-04.webp',
      '/catalogue/rope-series/ROP-008-05.webp',
      '/catalogue/rope-series/ROP-008-06.webp',
      '/catalogue/rope-series/ROP-008-07.webp',
      '/catalogue/rope-series/ROP-008-08.webp',
      '/catalogue/rope-series/ROP-008-09.webp',
    ],
    variants: [
      {
        id: 'rop-008-design-principal',
        name: 'cordage tressé rouge',
        imageUrl: '/catalogue/rope-series/ROP-008-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-008-02.webp',
          '/catalogue/rope-series/ROP-008-03.webp',
          '/catalogue/rope-series/ROP-008-04.webp',
          '/catalogue/rope-series/ROP-008-05.webp',
          '/catalogue/rope-series/ROP-008-06.webp',
          '/catalogue/rope-series/ROP-008-07.webp',
          '/catalogue/rope-series/ROP-008-08.webp',
          '/catalogue/rope-series/ROP-008-09.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage tressé',
      'Coloris rouge',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-009',
    sku: 'ROP-009',
    category: 'chair',
    name: 'Chaise de terrasse ETRETAT - tressage chêne',
    description:
      'Chaise de terrasse ETRETAT - tressage chêne pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-009-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-009-02.webp',
      '/catalogue/rope-series/ROP-009-03.webp',
      '/catalogue/rope-series/ROP-009-04.webp',
      '/catalogue/rope-series/ROP-009-05.webp',
      '/catalogue/rope-series/ROP-009-06.webp',
    ],
    variants: [
      {
        id: 'rop-009-design-principal',
        name: 'cordage tressé chêne',
        imageUrl: '/catalogue/rope-series/ROP-009-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-009-02.webp',
          '/catalogue/rope-series/ROP-009-03.webp',
          '/catalogue/rope-series/ROP-009-04.webp',
          '/catalogue/rope-series/ROP-009-05.webp',
          '/catalogue/rope-series/ROP-009-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage tressé',
      'Coloris chêne',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-010',
    sku: 'ROP-010',
    category: 'chair',
    name: 'Chaise de terrasse DINARD - tressage chêne',
    description:
      'Chaise de terrasse DINARD - tressage chêne pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-010-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-010-02.webp',
      '/catalogue/rope-series/ROP-010-03.webp',
      '/catalogue/rope-series/ROP-010-04.webp',
      '/catalogue/rope-series/ROP-010-05.webp',
      '/catalogue/rope-series/ROP-010-06.webp',
    ],
    variants: [
      {
        id: 'rop-010-design-principal',
        name: 'cordage tressé chêne',
        imageUrl: '/catalogue/rope-series/ROP-010-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-010-02.webp',
          '/catalogue/rope-series/ROP-010-03.webp',
          '/catalogue/rope-series/ROP-010-04.webp',
          '/catalogue/rope-series/ROP-010-05.webp',
          '/catalogue/rope-series/ROP-010-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage tressé',
      'Coloris chêne',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-011',
    sku: 'ROP-011',
    category: 'bench',
    name: 'Salon de terrasse cordage CAPRI - cordage câble bois',
    description:
      'Salon de terrasse cordage CAPRI - cordage câble bois pour zone lounge, piscine, rooftop, camping, hôtel et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 180x78x78 cm, poids 24 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 180,
      w: 78,
      h: 78,
    },
    cbmPerUnit: 0.45,
    weightKg: 24,
    moqUnits: 20,
    basePriceHt: 449,
    retailPriceRef: 786,
    ecoContribution: 1.2,
    mainImageUrl: '/catalogue/rope-series/ROP-011-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-011-02.webp',
      '/catalogue/rope-series/ROP-011-03.webp',
      '/catalogue/rope-series/ROP-011-04.webp',
      '/catalogue/rope-series/ROP-011-05.webp',
      '/catalogue/rope-series/ROP-011-06.webp',
    ],
    variants: [
      {
        id: 'rop-011-design-principal',
        name: 'câble tressé bois',
        imageUrl: '/catalogue/rope-series/ROP-011-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-011-02.webp',
          '/catalogue/rope-series/ROP-011-03.webp',
          '/catalogue/rope-series/ROP-011-04.webp',
          '/catalogue/rope-series/ROP-011-05.webp',
          '/catalogue/rope-series/ROP-011-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Salon cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif câble tressé',
      'Coloris bois',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-012',
    sku: 'ROP-012',
    category: 'bench',
    name: 'Salon de terrasse cordage COMO - tressage gris clair / blanc / gris',
    description:
      'Salon de terrasse cordage COMO - tressage gris clair / blanc / gris pour zone lounge, piscine, rooftop, camping, hôtel et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 180x78x78 cm, poids 24 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 180,
      w: 78,
      h: 78,
    },
    cbmPerUnit: 0.45,
    weightKg: 24,
    moqUnits: 20,
    basePriceHt: 449,
    retailPriceRef: 786,
    ecoContribution: 1.2,
    mainImageUrl: '/catalogue/rope-series/ROP-012-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-012-02.webp',
      '/catalogue/rope-series/ROP-012-03.webp',
      '/catalogue/rope-series/ROP-012-04.webp',
      '/catalogue/rope-series/ROP-012-05.webp',
      '/catalogue/rope-series/ROP-012-06.webp',
    ],
    variants: [
      {
        id: 'rop-012-design-principal',
        name: 'cordage tressé gris clair / blanc / gris',
        imageUrl: '/catalogue/rope-series/ROP-012-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-012-02.webp',
          '/catalogue/rope-series/ROP-012-03.webp',
          '/catalogue/rope-series/ROP-012-04.webp',
          '/catalogue/rope-series/ROP-012-05.webp',
          '/catalogue/rope-series/ROP-012-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Salon cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage tressé',
      'Coloris gris clair / blanc / gris',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-013',
    sku: 'ROP-013',
    category: 'table',
    name: 'Table de terrasse SORRENTO - tressage teck',
    description:
      'Table de terrasse SORRENTO - tressage teck pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 160x90x74 cm, poids 18 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 160,
      w: 90,
      h: 74,
    },
    cbmPerUnit: 0.18,
    weightKg: 18,
    moqUnits: 20,
    basePriceHt: 229,
    retailPriceRef: 401,
    ecoContribution: 0.8,
    mainImageUrl: '/catalogue/rope-series/ROP-013-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-013-02.webp',
      '/catalogue/rope-series/ROP-013-03.webp',
      '/catalogue/rope-series/ROP-013-04.webp',
      '/catalogue/rope-series/ROP-013-05.webp',
    ],
    variants: [
      {
        id: 'rop-013-design-principal',
        name: 'cordage tressé teck',
        imageUrl: '/catalogue/rope-series/ROP-013-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-013-02.webp',
          '/catalogue/rope-series/ROP-013-03.webp',
          '/catalogue/rope-series/ROP-013-04.webp',
          '/catalogue/rope-series/ROP-013-05.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Ensemble repas cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage tressé',
      'Coloris teck',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-014',
    sku: 'ROP-014',
    category: 'bench',
    name: 'Salon de terrasse cordage PORTOFINO - tressage',
    description:
      'Salon de terrasse cordage PORTOFINO - tressage pour zone lounge, piscine, rooftop, camping, hôtel et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 180x78x78 cm, poids 24 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 180,
      w: 78,
      h: 78,
    },
    cbmPerUnit: 0.45,
    weightKg: 24,
    moqUnits: 20,
    basePriceHt: 449,
    retailPriceRef: 786,
    ecoContribution: 1.2,
    mainImageUrl: '/catalogue/rope-series/ROP-014-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-014-02.webp',
      '/catalogue/rope-series/ROP-014-03.webp',
      '/catalogue/rope-series/ROP-014-04.webp',
      '/catalogue/rope-series/ROP-014-05.webp',
      '/catalogue/rope-series/ROP-014-06.webp',
    ],
    variants: [
      {
        id: 'rop-014-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-014-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-014-02.webp',
          '/catalogue/rope-series/ROP-014-03.webp',
          '/catalogue/rope-series/ROP-014-04.webp',
          '/catalogue/rope-series/ROP-014-05.webp',
          '/catalogue/rope-series/ROP-014-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Salon cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage tressé',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-015',
    sku: 'ROP-015',
    category: 'bench',
    name: 'Salon de terrasse cordage AMALFI - tressage',
    description:
      'Salon de terrasse cordage AMALFI - tressage pour zone lounge, piscine, rooftop, camping, hôtel et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 180x78x78 cm, poids 24 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 180,
      w: 78,
      h: 78,
    },
    cbmPerUnit: 0.45,
    weightKg: 24,
    moqUnits: 20,
    basePriceHt: 449,
    retailPriceRef: 786,
    ecoContribution: 1.2,
    mainImageUrl: '/catalogue/rope-series/ROP-015-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-015-02.webp',
      '/catalogue/rope-series/ROP-015-03.webp',
      '/catalogue/rope-series/ROP-015-04.webp',
      '/catalogue/rope-series/ROP-015-05.webp',
      '/catalogue/rope-series/ROP-015-06.webp',
    ],
    variants: [
      {
        id: 'rop-015-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-015-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-015-02.webp',
          '/catalogue/rope-series/ROP-015-03.webp',
          '/catalogue/rope-series/ROP-015-04.webp',
          '/catalogue/rope-series/ROP-015-05.webp',
          '/catalogue/rope-series/ROP-015-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Salon cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage tressé',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-016',
    sku: 'ROP-016',
    category: 'table',
    name: 'Table de terrasse SIENA - tressage marron / rouge',
    description:
      'Table de terrasse SIENA - tressage marron / rouge pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 160x90x74 cm, poids 18 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 160,
      w: 90,
      h: 74,
    },
    cbmPerUnit: 0.18,
    weightKg: 18,
    moqUnits: 20,
    basePriceHt: 229,
    retailPriceRef: 401,
    ecoContribution: 0.8,
    mainImageUrl: '/catalogue/rope-series/ROP-016-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-016-02.webp',
      '/catalogue/rope-series/ROP-016-03.webp',
      '/catalogue/rope-series/ROP-016-04.webp',
      '/catalogue/rope-series/ROP-016-05.webp',
      '/catalogue/rope-series/ROP-016-06.webp',
    ],
    variants: [
      {
        id: 'rop-016-design-principal',
        name: 'cordage tressé marron / rouge',
        imageUrl: '/catalogue/rope-series/ROP-016-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-016-02.webp',
          '/catalogue/rope-series/ROP-016-03.webp',
          '/catalogue/rope-series/ROP-016-04.webp',
          '/catalogue/rope-series/ROP-016-05.webp',
          '/catalogue/rope-series/ROP-016-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Ensemble repas cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage tressé',
      'Coloris marron / rouge',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-017',
    sku: 'ROP-017',
    category: 'bench',
    name: 'Salon de terrasse cordage FLORENCE - tressage noir',
    description:
      'Salon de terrasse cordage FLORENCE - tressage noir pour zone lounge, piscine, rooftop, camping, hôtel et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 180x78x78 cm, poids 24 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 180,
      w: 78,
      h: 78,
    },
    cbmPerUnit: 0.45,
    weightKg: 24,
    moqUnits: 20,
    basePriceHt: 449,
    retailPriceRef: 786,
    ecoContribution: 1.2,
    mainImageUrl: '/catalogue/rope-series/ROP-017-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-017-02.webp',
      '/catalogue/rope-series/ROP-017-03.webp',
      '/catalogue/rope-series/ROP-017-04.webp',
      '/catalogue/rope-series/ROP-017-05.webp',
      '/catalogue/rope-series/ROP-017-06.webp',
    ],
    variants: [
      {
        id: 'rop-017-design-principal',
        name: 'cordage tressé noir',
        imageUrl: '/catalogue/rope-series/ROP-017-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-017-02.webp',
          '/catalogue/rope-series/ROP-017-03.webp',
          '/catalogue/rope-series/ROP-017-04.webp',
          '/catalogue/rope-series/ROP-017-05.webp',
          '/catalogue/rope-series/ROP-017-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Salon cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage tressé',
      'Coloris noir',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-018',
    sku: 'ROP-018',
    category: 'bench',
    name: 'Salon de terrasse cordage VERONA - tressage',
    description:
      'Salon de terrasse cordage VERONA - tressage pour zone lounge, piscine, rooftop, camping, hôtel et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 180x78x78 cm, poids 24 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 180,
      w: 78,
      h: 78,
    },
    cbmPerUnit: 0.45,
    weightKg: 24,
    moqUnits: 20,
    basePriceHt: 449,
    retailPriceRef: 786,
    ecoContribution: 1.2,
    mainImageUrl: '/catalogue/rope-series/ROP-018-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-018-02.webp',
      '/catalogue/rope-series/ROP-018-03.webp',
      '/catalogue/rope-series/ROP-018-04.webp',
      '/catalogue/rope-series/ROP-018-05.webp',
      '/catalogue/rope-series/ROP-018-06.webp',
    ],
    variants: [
      {
        id: 'rop-018-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-018-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-018-02.webp',
          '/catalogue/rope-series/ROP-018-03.webp',
          '/catalogue/rope-series/ROP-018-04.webp',
          '/catalogue/rope-series/ROP-018-05.webp',
          '/catalogue/rope-series/ROP-018-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Salon cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage tressé',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-019',
    sku: 'ROP-019',
    category: 'bench',
    name: 'Salon de terrasse cordage RAVENNA - tressage',
    description:
      'Salon de terrasse cordage RAVENNA - tressage pour zone lounge, piscine, rooftop, camping, hôtel et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 180x78x78 cm, poids 24 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 180,
      w: 78,
      h: 78,
    },
    cbmPerUnit: 0.45,
    weightKg: 24,
    moqUnits: 20,
    basePriceHt: 449,
    retailPriceRef: 786,
    ecoContribution: 1.2,
    mainImageUrl: '/catalogue/rope-series/ROP-019-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-019-02.webp',
      '/catalogue/rope-series/ROP-019-03.webp',
      '/catalogue/rope-series/ROP-019-04.webp',
      '/catalogue/rope-series/ROP-019-05.webp',
      '/catalogue/rope-series/ROP-019-06.webp',
    ],
    variants: [
      {
        id: 'rop-019-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-019-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-019-02.webp',
          '/catalogue/rope-series/ROP-019-03.webp',
          '/catalogue/rope-series/ROP-019-04.webp',
          '/catalogue/rope-series/ROP-019-05.webp',
          '/catalogue/rope-series/ROP-019-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Salon cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage tressé',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-020',
    sku: 'ROP-020',
    category: 'table',
    name: 'Table de terrasse BELLAGIO - tressage bois',
    description:
      'Table de terrasse BELLAGIO - tressage bois pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 160x90x74 cm, poids 18 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 160,
      w: 90,
      h: 74,
    },
    cbmPerUnit: 0.18,
    weightKg: 18,
    moqUnits: 20,
    basePriceHt: 229,
    retailPriceRef: 401,
    ecoContribution: 0.8,
    mainImageUrl: '/catalogue/rope-series/ROP-020-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-020-02.webp',
      '/catalogue/rope-series/ROP-020-03.webp',
      '/catalogue/rope-series/ROP-020-04.webp',
      '/catalogue/rope-series/ROP-020-05.webp',
      '/catalogue/rope-series/ROP-020-06.webp',
    ],
    variants: [
      {
        id: 'rop-020-design-principal',
        name: 'cordage tressé bois',
        imageUrl: '/catalogue/rope-series/ROP-020-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-020-02.webp',
          '/catalogue/rope-series/ROP-020-03.webp',
          '/catalogue/rope-series/ROP-020-04.webp',
          '/catalogue/rope-series/ROP-020-05.webp',
          '/catalogue/rope-series/ROP-020-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Table cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage tressé',
      'Coloris bois',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-021',
    sku: 'ROP-021',
    category: 'chair',
    name: 'Chaise de terrasse SEVILLE - cordage outdoor',
    description:
      'Chaise de terrasse SEVILLE - cordage outdoor pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-021-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-021-02.webp',
      '/catalogue/rope-series/ROP-021-03.webp',
      '/catalogue/rope-series/ROP-021-04.webp',
      '/catalogue/rope-series/ROP-021-05.webp',
      '/catalogue/rope-series/ROP-021-06.webp',
      '/catalogue/rope-series/ROP-021-07.webp',
      '/catalogue/rope-series/ROP-021-08.webp',
      '/catalogue/rope-series/ROP-021-09.webp',
    ],
    variants: [
      {
        id: 'rop-021-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-021-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-021-02.webp',
          '/catalogue/rope-series/ROP-021-03.webp',
          '/catalogue/rope-series/ROP-021-04.webp',
          '/catalogue/rope-series/ROP-021-05.webp',
          '/catalogue/rope-series/ROP-021-06.webp',
          '/catalogue/rope-series/ROP-021-07.webp',
          '/catalogue/rope-series/ROP-021-08.webp',
          '/catalogue/rope-series/ROP-021-09.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-022',
    sku: 'ROP-022',
    category: 'chair',
    name: 'Chaise de terrasse VALENCIA - tressage',
    description:
      'Chaise de terrasse VALENCIA - tressage pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 55x58x106 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 55,
      w: 58,
      h: 106,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-022-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-022-02.webp',
      '/catalogue/rope-series/ROP-022-03.webp',
      '/catalogue/rope-series/ROP-022-04.webp',
      '/catalogue/rope-series/ROP-022-05.webp',
      '/catalogue/rope-series/ROP-022-06.webp',
    ],
    variants: [
      {
        id: 'rop-022-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-022-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-022-02.webp',
          '/catalogue/rope-series/ROP-022-03.webp',
          '/catalogue/rope-series/ROP-022-04.webp',
          '/catalogue/rope-series/ROP-022-05.webp',
          '/catalogue/rope-series/ROP-022-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise haute cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage tressé',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-023',
    sku: 'ROP-023',
    category: 'chair',
    name: 'Chaise de terrasse MALAGA - cordage outdoor',
    description:
      'Chaise de terrasse MALAGA - cordage outdoor pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-023-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-023-02.webp',
      '/catalogue/rope-series/ROP-023-03.webp',
      '/catalogue/rope-series/ROP-023-04.webp',
    ],
    variants: [
      {
        id: 'rop-023-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-023-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-023-02.webp',
          '/catalogue/rope-series/ROP-023-03.webp',
          '/catalogue/rope-series/ROP-023-04.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-024',
    sku: 'ROP-024',
    category: 'chair',
    name: 'Chaise de terrasse PALMA - tressage blanc',
    description:
      'Chaise de terrasse PALMA - tressage blanc pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-024-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-024-02.webp',
      '/catalogue/rope-series/ROP-024-03.webp',
      '/catalogue/rope-series/ROP-024-04.webp',
      '/catalogue/rope-series/ROP-024-05.webp',
    ],
    variants: [
      {
        id: 'rop-024-design-principal',
        name: 'cordage tressé blanc',
        imageUrl: '/catalogue/rope-series/ROP-024-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-024-02.webp',
          '/catalogue/rope-series/ROP-024-03.webp',
          '/catalogue/rope-series/ROP-024-04.webp',
          '/catalogue/rope-series/ROP-024-05.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage tressé',
      'Coloris blanc',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-025',
    sku: 'ROP-025',
    category: 'chair',
    name: 'Chaise de terrasse IBIZA - cordage outdoor',
    description:
      'Chaise de terrasse IBIZA - cordage outdoor pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-025-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-025-02.webp',
      '/catalogue/rope-series/ROP-025-03.webp',
      '/catalogue/rope-series/ROP-025-04.webp',
      '/catalogue/rope-series/ROP-025-05.webp',
      '/catalogue/rope-series/ROP-025-06.webp',
      '/catalogue/rope-series/ROP-025-07.webp',
    ],
    variants: [
      {
        id: 'rop-025-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-025-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-025-02.webp',
          '/catalogue/rope-series/ROP-025-03.webp',
          '/catalogue/rope-series/ROP-025-04.webp',
          '/catalogue/rope-series/ROP-025-05.webp',
          '/catalogue/rope-series/ROP-025-06.webp',
          '/catalogue/rope-series/ROP-025-07.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-026',
    sku: 'ROP-026',
    category: 'chair',
    name: 'Chaise de terrasse CORDOBA - cordage outdoor',
    description:
      'Chaise de terrasse CORDOBA - cordage outdoor pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-026-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-026-02.webp',
      '/catalogue/rope-series/ROP-026-03.webp',
      '/catalogue/rope-series/ROP-026-04.webp',
      '/catalogue/rope-series/ROP-026-05.webp',
      '/catalogue/rope-series/ROP-026-06.webp',
      '/catalogue/rope-series/ROP-026-07.webp',
      '/catalogue/rope-series/ROP-026-08.webp',
      '/catalogue/rope-series/ROP-026-09.webp',
    ],
    variants: [
      {
        id: 'rop-026-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-026-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-026-02.webp',
          '/catalogue/rope-series/ROP-026-03.webp',
          '/catalogue/rope-series/ROP-026-04.webp',
          '/catalogue/rope-series/ROP-026-05.webp',
          '/catalogue/rope-series/ROP-026-06.webp',
          '/catalogue/rope-series/ROP-026-07.webp',
          '/catalogue/rope-series/ROP-026-08.webp',
          '/catalogue/rope-series/ROP-026-09.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-027',
    sku: 'ROP-027',
    category: 'chair',
    name: 'Chaise de terrasse GRANADA - cordage outdoor',
    description:
      'Chaise de terrasse GRANADA - cordage outdoor pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-027-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-027-02.webp',
      '/catalogue/rope-series/ROP-027-03.webp',
      '/catalogue/rope-series/ROP-027-04.webp',
      '/catalogue/rope-series/ROP-027-05.webp',
    ],
    variants: [
      {
        id: 'rop-027-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-027-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-027-02.webp',
          '/catalogue/rope-series/ROP-027-03.webp',
          '/catalogue/rope-series/ROP-027-04.webp',
          '/catalogue/rope-series/ROP-027-05.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-028',
    sku: 'ROP-028',
    category: 'chair',
    name: 'Chaise de terrasse TOLEDO - cordage outdoor',
    description:
      'Chaise de terrasse TOLEDO - cordage outdoor pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-028-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-028-02.webp',
      '/catalogue/rope-series/ROP-028-03.webp',
      '/catalogue/rope-series/ROP-028-04.webp',
      '/catalogue/rope-series/ROP-028-05.webp',
      '/catalogue/rope-series/ROP-028-06.webp',
      '/catalogue/rope-series/ROP-028-07.webp',
      '/catalogue/rope-series/ROP-028-08.webp',
    ],
    variants: [
      {
        id: 'rop-028-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-028-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-028-02.webp',
          '/catalogue/rope-series/ROP-028-03.webp',
          '/catalogue/rope-series/ROP-028-04.webp',
          '/catalogue/rope-series/ROP-028-05.webp',
          '/catalogue/rope-series/ROP-028-06.webp',
          '/catalogue/rope-series/ROP-028-07.webp',
          '/catalogue/rope-series/ROP-028-08.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-029',
    sku: 'ROP-029',
    category: 'chair',
    name: 'Chaise de terrasse MARBELLA - cordage outdoor',
    description:
      'Chaise de terrasse MARBELLA - cordage outdoor pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-029-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-029-02.webp',
      '/catalogue/rope-series/ROP-029-03.webp',
      '/catalogue/rope-series/ROP-029-04.webp',
      '/catalogue/rope-series/ROP-029-05.webp',
      '/catalogue/rope-series/ROP-029-06.webp',
      '/catalogue/rope-series/ROP-029-07.webp',
      '/catalogue/rope-series/ROP-029-08.webp',
    ],
    variants: [
      {
        id: 'rop-029-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-029-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-029-02.webp',
          '/catalogue/rope-series/ROP-029-03.webp',
          '/catalogue/rope-series/ROP-029-04.webp',
          '/catalogue/rope-series/ROP-029-05.webp',
          '/catalogue/rope-series/ROP-029-06.webp',
          '/catalogue/rope-series/ROP-029-07.webp',
          '/catalogue/rope-series/ROP-029-08.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-030',
    sku: 'ROP-030',
    category: 'chair',
    name: 'Chaise de terrasse RONDA - cordage outdoor',
    description:
      'Chaise de terrasse RONDA - cordage outdoor pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-030-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-030-02.webp',
      '/catalogue/rope-series/ROP-030-03.webp',
      '/catalogue/rope-series/ROP-030-04.webp',
      '/catalogue/rope-series/ROP-030-05.webp',
      '/catalogue/rope-series/ROP-030-06.webp',
      '/catalogue/rope-series/ROP-030-07.webp',
      '/catalogue/rope-series/ROP-030-08.webp',
    ],
    variants: [
      {
        id: 'rop-030-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-030-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-030-02.webp',
          '/catalogue/rope-series/ROP-030-03.webp',
          '/catalogue/rope-series/ROP-030-04.webp',
          '/catalogue/rope-series/ROP-030-05.webp',
          '/catalogue/rope-series/ROP-030-06.webp',
          '/catalogue/rope-series/ROP-030-07.webp',
          '/catalogue/rope-series/ROP-030-08.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-031',
    sku: 'ROP-031',
    category: 'chair',
    name: 'Chaise de terrasse ATHENES - cordage outdoor',
    description:
      'Chaise de terrasse ATHENES - cordage outdoor pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-031-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-031-02.webp',
      '/catalogue/rope-series/ROP-031-03.webp',
      '/catalogue/rope-series/ROP-031-04.webp',
    ],
    variants: [
      {
        id: 'rop-031-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-031-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-031-02.webp',
          '/catalogue/rope-series/ROP-031-03.webp',
          '/catalogue/rope-series/ROP-031-04.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-032',
    sku: 'ROP-032',
    category: 'chair',
    name: 'Chaise de terrasse PAROS - cordage outdoor',
    description:
      'Chaise de terrasse PAROS - cordage outdoor pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-032-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-032-02.webp',
      '/catalogue/rope-series/ROP-032-03.webp',
      '/catalogue/rope-series/ROP-032-04.webp',
      '/catalogue/rope-series/ROP-032-05.webp',
      '/catalogue/rope-series/ROP-032-06.webp',
      '/catalogue/rope-series/ROP-032-07.webp',
    ],
    variants: [
      {
        id: 'rop-032-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-032-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-032-02.webp',
          '/catalogue/rope-series/ROP-032-03.webp',
          '/catalogue/rope-series/ROP-032-04.webp',
          '/catalogue/rope-series/ROP-032-05.webp',
          '/catalogue/rope-series/ROP-032-06.webp',
          '/catalogue/rope-series/ROP-032-07.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-033',
    sku: 'ROP-033',
    category: 'chair',
    name: 'Chaise de terrasse NAXOS - cordage outdoor',
    description:
      'Chaise de terrasse NAXOS - cordage outdoor pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-033-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-033-02.webp',
      '/catalogue/rope-series/ROP-033-03.webp',
    ],
    variants: [
      {
        id: 'rop-033-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-033-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-033-02.webp',
          '/catalogue/rope-series/ROP-033-03.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-034',
    sku: 'ROP-034',
    category: 'chair',
    name: 'Chaise de terrasse HYDRA - cordage outdoor',
    description:
      'Chaise de terrasse HYDRA - cordage outdoor pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-034-01.webp',
    galleryUrls: ['/catalogue/rope-series/ROP-034-02.webp'],
    variants: [
      {
        id: 'rop-034-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-034-01.webp',
        galleryUrls: ['/catalogue/rope-series/ROP-034-02.webp'],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-035',
    sku: 'ROP-035',
    category: 'chair',
    name: 'Chaise de terrasse CORFOU - cordage outdoor',
    description:
      'Chaise de terrasse CORFOU - cordage outdoor pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-035-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-035-02.webp',
      '/catalogue/rope-series/ROP-035-03.webp',
      '/catalogue/rope-series/ROP-035-04.webp',
      '/catalogue/rope-series/ROP-035-05.webp',
      '/catalogue/rope-series/ROP-035-06.webp',
      '/catalogue/rope-series/ROP-035-07.webp',
      '/catalogue/rope-series/ROP-035-08.webp',
    ],
    variants: [
      {
        id: 'rop-035-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-035-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-035-02.webp',
          '/catalogue/rope-series/ROP-035-03.webp',
          '/catalogue/rope-series/ROP-035-04.webp',
          '/catalogue/rope-series/ROP-035-05.webp',
          '/catalogue/rope-series/ROP-035-06.webp',
          '/catalogue/rope-series/ROP-035-07.webp',
          '/catalogue/rope-series/ROP-035-08.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-036',
    sku: 'ROP-036',
    category: 'chair',
    name: 'Chaise de terrasse MYKONOS - cordage outdoor',
    description:
      'Chaise de terrasse MYKONOS - cordage outdoor pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-036-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-036-02.webp',
      '/catalogue/rope-series/ROP-036-03.webp',
      '/catalogue/rope-series/ROP-036-04.webp',
      '/catalogue/rope-series/ROP-036-05.webp',
      '/catalogue/rope-series/ROP-036-06.webp',
    ],
    variants: [
      {
        id: 'rop-036-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-036-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-036-02.webp',
          '/catalogue/rope-series/ROP-036-03.webp',
          '/catalogue/rope-series/ROP-036-04.webp',
          '/catalogue/rope-series/ROP-036-05.webp',
          '/catalogue/rope-series/ROP-036-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-037',
    sku: 'ROP-037',
    category: 'chair',
    name: 'Chaise de terrasse SANTORIN - cordage outdoor',
    description:
      'Chaise de terrasse SANTORIN - cordage outdoor pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-037-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-037-02.webp',
      '/catalogue/rope-series/ROP-037-03.webp',
      '/catalogue/rope-series/ROP-037-04.webp',
      '/catalogue/rope-series/ROP-037-05.webp',
    ],
    variants: [
      {
        id: 'rop-037-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-037-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-037-02.webp',
          '/catalogue/rope-series/ROP-037-03.webp',
          '/catalogue/rope-series/ROP-037-04.webp',
          '/catalogue/rope-series/ROP-037-05.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-038',
    sku: 'ROP-038',
    category: 'chair',
    name: 'Chaise de terrasse MILOS - cordage outdoor',
    description:
      'Chaise de terrasse MILOS - cordage outdoor pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-038-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-038-02.webp',
      '/catalogue/rope-series/ROP-038-03.webp',
    ],
    variants: [
      {
        id: 'rop-038-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-038-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-038-02.webp',
          '/catalogue/rope-series/ROP-038-03.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-039',
    sku: 'ROP-039',
    category: 'chair',
    name: 'Chaise de terrasse RHODES - cordage outdoor',
    description:
      'Chaise de terrasse RHODES - cordage outdoor pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-039-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-039-02.webp',
      '/catalogue/rope-series/ROP-039-03.webp',
      '/catalogue/rope-series/ROP-039-04.webp',
      '/catalogue/rope-series/ROP-039-05.webp',
      '/catalogue/rope-series/ROP-039-06.webp',
      '/catalogue/rope-series/ROP-039-07.webp',
      '/catalogue/rope-series/ROP-039-08.webp',
    ],
    variants: [
      {
        id: 'rop-039-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-039-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-039-02.webp',
          '/catalogue/rope-series/ROP-039-03.webp',
          '/catalogue/rope-series/ROP-039-04.webp',
          '/catalogue/rope-series/ROP-039-05.webp',
          '/catalogue/rope-series/ROP-039-06.webp',
          '/catalogue/rope-series/ROP-039-07.webp',
          '/catalogue/rope-series/ROP-039-08.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-040',
    sku: 'ROP-040',
    category: 'chair',
    name: 'Chaise de terrasse PATMOS - cordage outdoor',
    description:
      'Chaise de terrasse PATMOS - cordage outdoor pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-040-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-040-02.webp',
      '/catalogue/rope-series/ROP-040-03.webp',
      '/catalogue/rope-series/ROP-040-04.webp',
    ],
    variants: [
      {
        id: 'rop-040-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-040-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-040-02.webp',
          '/catalogue/rope-series/ROP-040-03.webp',
          '/catalogue/rope-series/ROP-040-04.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-041',
    sku: 'ROP-041',
    category: 'chair',
    name: 'Chaise de terrasse ATLAS - cordage outdoor',
    description:
      'Chaise de terrasse ATLAS - cordage outdoor pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-041-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-041-02.webp',
      '/catalogue/rope-series/ROP-041-03.webp',
      '/catalogue/rope-series/ROP-041-04.webp',
      '/catalogue/rope-series/ROP-041-05.webp',
      '/catalogue/rope-series/ROP-041-06.webp',
      '/catalogue/rope-series/ROP-041-07.webp',
      '/catalogue/rope-series/ROP-041-08.webp',
    ],
    variants: [
      {
        id: 'rop-041-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-041-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-041-02.webp',
          '/catalogue/rope-series/ROP-041-03.webp',
          '/catalogue/rope-series/ROP-041-04.webp',
          '/catalogue/rope-series/ROP-041-05.webp',
          '/catalogue/rope-series/ROP-041-06.webp',
          '/catalogue/rope-series/ROP-041-07.webp',
          '/catalogue/rope-series/ROP-041-08.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-042',
    sku: 'ROP-042',
    category: 'chair',
    name: 'Chaise de terrasse MEDINA - cordage outdoor',
    description:
      'Chaise de terrasse MEDINA - cordage outdoor pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-042-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-042-02.webp',
      '/catalogue/rope-series/ROP-042-03.webp',
      '/catalogue/rope-series/ROP-042-04.webp',
      '/catalogue/rope-series/ROP-042-05.webp',
      '/catalogue/rope-series/ROP-042-06.webp',
    ],
    variants: [
      {
        id: 'rop-042-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-042-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-042-02.webp',
          '/catalogue/rope-series/ROP-042-03.webp',
          '/catalogue/rope-series/ROP-042-04.webp',
          '/catalogue/rope-series/ROP-042-05.webp',
          '/catalogue/rope-series/ROP-042-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-043',
    sku: 'ROP-043',
    category: 'chair',
    name: 'Chaise de terrasse OASIS - cordage outdoor',
    description:
      'Chaise de terrasse OASIS - cordage outdoor pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-043-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-043-02.webp',
      '/catalogue/rope-series/ROP-043-03.webp',
    ],
    variants: [
      {
        id: 'rop-043-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-043-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-043-02.webp',
          '/catalogue/rope-series/ROP-043-03.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-044',
    sku: 'ROP-044',
    category: 'table',
    name: 'Table de terrasse RIVAGE - tressage bois',
    description:
      'Table de terrasse RIVAGE - tressage bois pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 160x90x74 cm, poids 18 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 160,
      w: 90,
      h: 74,
    },
    cbmPerUnit: 0.18,
    weightKg: 18,
    moqUnits: 20,
    basePriceHt: 229,
    retailPriceRef: 401,
    ecoContribution: 0.8,
    mainImageUrl: '/catalogue/rope-series/ROP-044-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-044-02.webp',
      '/catalogue/rope-series/ROP-044-03.webp',
      '/catalogue/rope-series/ROP-044-04.webp',
      '/catalogue/rope-series/ROP-044-05.webp',
      '/catalogue/rope-series/ROP-044-06.webp',
    ],
    variants: [
      {
        id: 'rop-044-design-principal',
        name: 'cordage tressé bois',
        imageUrl: '/catalogue/rope-series/ROP-044-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-044-02.webp',
          '/catalogue/rope-series/ROP-044-03.webp',
          '/catalogue/rope-series/ROP-044-04.webp',
          '/catalogue/rope-series/ROP-044-05.webp',
          '/catalogue/rope-series/ROP-044-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Table cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage tressé',
      'Coloris bois',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-045',
    sku: 'ROP-045',
    category: 'chair',
    name: 'Chaise de terrasse CALANQUE - tressage',
    description:
      'Chaise de terrasse CALANQUE - tressage pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-045-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-045-02.webp',
      '/catalogue/rope-series/ROP-045-03.webp',
      '/catalogue/rope-series/ROP-045-04.webp',
    ],
    variants: [
      {
        id: 'rop-045-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-045-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-045-02.webp',
          '/catalogue/rope-series/ROP-045-03.webp',
          '/catalogue/rope-series/ROP-045-04.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage tressé',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-046',
    sku: 'ROP-046',
    category: 'chair',
    name: 'Chaise de terrasse AZUR - cordage outdoor',
    description:
      'Chaise de terrasse AZUR - cordage outdoor pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-046-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-046-02.webp',
      '/catalogue/rope-series/ROP-046-03.webp',
      '/catalogue/rope-series/ROP-046-04.webp',
    ],
    variants: [
      {
        id: 'rop-046-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-046-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-046-02.webp',
          '/catalogue/rope-series/ROP-046-03.webp',
          '/catalogue/rope-series/ROP-046-04.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-047',
    sku: 'ROP-047',
    category: 'table',
    name: 'Table de terrasse ESTEREL - bois',
    description:
      'Table de terrasse ESTEREL - bois pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 160x90x74 cm, poids 18 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 160,
      w: 90,
      h: 74,
    },
    cbmPerUnit: 0.18,
    weightKg: 18,
    moqUnits: 20,
    basePriceHt: 229,
    retailPriceRef: 401,
    ecoContribution: 0.8,
    mainImageUrl: '/catalogue/rope-series/ROP-047-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-047-02.webp',
      '/catalogue/rope-series/ROP-047-03.webp',
      '/catalogue/rope-series/ROP-047-04.webp',
      '/catalogue/rope-series/ROP-047-05.webp',
      '/catalogue/rope-series/ROP-047-06.webp',
    ],
    variants: [
      {
        id: 'rop-047-design-principal',
        name: 'cordage bois',
        imageUrl: '/catalogue/rope-series/ROP-047-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-047-02.webp',
          '/catalogue/rope-series/ROP-047-03.webp',
          '/catalogue/rope-series/ROP-047-04.webp',
          '/catalogue/rope-series/ROP-047-05.webp',
          '/catalogue/rope-series/ROP-047-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Table cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage',
      'Coloris bois',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'rope-rop-048',
    sku: 'ROP-048',
    category: 'chair',
    name: 'Chaise de terrasse LUBERON - tressage',
    description:
      'Chaise de terrasse LUBERON - tressage pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en cordage outdoor et structure aluminium, dimensions 52x60x82 cm, poids 5.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 52,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 5.2,
    moqUnits: 50,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/rope-series/ROP-048-01.webp',
    galleryUrls: [
      '/catalogue/rope-series/ROP-048-02.webp',
      '/catalogue/rope-series/ROP-048-03.webp',
      '/catalogue/rope-series/ROP-048-04.webp',
    ],
    variants: [
      {
        id: 'rop-048-design-principal',
        name: 'Design présenté',
        imageUrl: '/catalogue/rope-series/ROP-048-01.webp',
        galleryUrls: [
          '/catalogue/rope-series/ROP-048-02.webp',
          '/catalogue/rope-series/ROP-048-03.webp',
          '/catalogue/rope-series/ROP-048-04.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise cordage',
      'Structure aluminium',
      'Finition cordage outdoor',
      'Motif cordage tressé',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
] as Product[]
