import type { Product } from './products'

// Catalogue piètement de table anonymisé. Ne contient aucune source fournisseur.
// Photos locales groupées par SKU dans public/catalogue/table-base-series.
export const TABLE_BASE_PRODUCTS: Product[] = [
  {
    id: 'table-base-tba-001',
    sku: 'TBA-001',
    category: 'table',
    name: 'Piètement de table AZUR - plateau rabattable',
    description:
      'Piètement de table AZUR - plateau rabattable pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en piètement aluminium, dimensions 70x70x72 cm, poids 8.5 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Compatible avec projets de plateaux et implantations terrasse en volume.',
    dimensions: {
      l: 70,
      w: 70,
      h: 72,
    },
    cbmPerUnit: 0.055,
    weightKg: 8.5,
    moqUnits: 20,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.65,
    mainImageUrl: '/catalogue/table-base-series/TBA-001-01.webp',
    galleryUrls: [
      '/catalogue/table-base-series/TBA-001-02.webp',
      '/catalogue/table-base-series/TBA-001-03.webp',
      '/catalogue/table-base-series/TBA-001-04.webp',
      '/catalogue/table-base-series/TBA-001-05.webp',
      '/catalogue/table-base-series/TBA-001-06.webp',
    ],
    variants: [
      {
        id: 'tba-001-design-principal',
        name: 'plateau rabattable',
        imageUrl: '/catalogue/table-base-series/TBA-001-01.webp',
        galleryUrls: [
          '/catalogue/table-base-series/TBA-001-02.webp',
          '/catalogue/table-base-series/TBA-001-03.webp',
          '/catalogue/table-base-series/TBA-001-04.webp',
          '/catalogue/table-base-series/TBA-001-05.webp',
          '/catalogue/table-base-series/TBA-001-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Piètement rabattable de table',
      'Structure aluminium',
      'Plateau rabattable',
      'Compatible projets terrasse CHR',
      'Photos groupées par fiche produit',
      'Plateau à sélectionner séparément',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'table-base-tba-002',
    sku: 'TBA-002',
    category: 'table',
    name: 'Piètement de table ESTEREL - double colonne',
    description:
      'Piètement de table ESTEREL - double colonne pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en piètement aluminium, dimensions 110x62x72 cm, poids 14 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Compatible avec projets de plateaux et implantations terrasse en volume.',
    dimensions: {
      l: 110,
      w: 62,
      h: 72,
    },
    cbmPerUnit: 0.09,
    weightKg: 14,
    moqUnits: 20,
    basePriceHt: 149,
    retailPriceRef: 261,
    ecoContribution: 0.65,
    mainImageUrl: '/catalogue/table-base-series/TBA-002-01.webp',
    galleryUrls: [
      '/catalogue/table-base-series/TBA-002-02.webp',
      '/catalogue/table-base-series/TBA-002-03.webp',
      '/catalogue/table-base-series/TBA-002-04.webp',
      '/catalogue/table-base-series/TBA-002-05.webp',
      '/catalogue/table-base-series/TBA-002-06.webp',
    ],
    variants: [
      {
        id: 'tba-002-design-principal',
        name: 'double colonne',
        imageUrl: '/catalogue/table-base-series/TBA-002-01.webp',
        galleryUrls: [
          '/catalogue/table-base-series/TBA-002-02.webp',
          '/catalogue/table-base-series/TBA-002-03.webp',
          '/catalogue/table-base-series/TBA-002-04.webp',
          '/catalogue/table-base-series/TBA-002-05.webp',
          '/catalogue/table-base-series/TBA-002-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Piètement double de table',
      'Structure aluminium',
      'Double colonne',
      'Compatible projets terrasse CHR',
      'Photos groupées par fiche produit',
      'Plateau à sélectionner séparément',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'table-base-tba-003',
    sku: 'TBA-003',
    category: 'table',
    name: 'Piètement de table LUBERON - style classique',
    description:
      'Piètement de table LUBERON - style classique pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en piètement aluminium, dimensions 70x70x72 cm, poids 8.5 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Compatible avec projets de plateaux et implantations terrasse en volume.',
    dimensions: {
      l: 70,
      w: 70,
      h: 72,
    },
    cbmPerUnit: 0.055,
    weightKg: 8.5,
    moqUnits: 20,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.65,
    mainImageUrl: '/catalogue/table-base-series/TBA-003-01.webp',
    galleryUrls: [
      '/catalogue/table-base-series/TBA-003-02.webp',
      '/catalogue/table-base-series/TBA-003-03.webp',
      '/catalogue/table-base-series/TBA-003-04.webp',
      '/catalogue/table-base-series/TBA-003-05.webp',
      '/catalogue/table-base-series/TBA-003-06.webp',
    ],
    variants: [
      {
        id: 'tba-003-design-principal',
        name: 'style bistrot classique',
        imageUrl: '/catalogue/table-base-series/TBA-003-01.webp',
        galleryUrls: [
          '/catalogue/table-base-series/TBA-003-02.webp',
          '/catalogue/table-base-series/TBA-003-03.webp',
          '/catalogue/table-base-series/TBA-003-04.webp',
          '/catalogue/table-base-series/TBA-003-05.webp',
          '/catalogue/table-base-series/TBA-003-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Piètement de table bistrot',
      'Structure aluminium',
      'Style bistrot classique',
      'Compatible projets terrasse CHR',
      'Photos groupées par fiche produit',
      'Plateau à sélectionner séparément',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'table-base-tba-004',
    sku: 'TBA-004',
    category: 'table',
    name: 'Piètement de table CAMARGUE - style classique',
    description:
      'Piètement de table CAMARGUE - style classique pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en piètement aluminium, dimensions 110x62x72 cm, poids 14 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Compatible avec projets de plateaux et implantations terrasse en volume.',
    dimensions: {
      l: 110,
      w: 62,
      h: 72,
    },
    cbmPerUnit: 0.09,
    weightKg: 14,
    moqUnits: 20,
    basePriceHt: 149,
    retailPriceRef: 261,
    ecoContribution: 0.65,
    mainImageUrl: '/catalogue/table-base-series/TBA-004-01.webp',
    galleryUrls: [
      '/catalogue/table-base-series/TBA-004-02.webp',
      '/catalogue/table-base-series/TBA-004-03.webp',
      '/catalogue/table-base-series/TBA-004-04.webp',
      '/catalogue/table-base-series/TBA-004-05.webp',
      '/catalogue/table-base-series/TBA-004-06.webp',
    ],
    variants: [
      {
        id: 'tba-004-design-principal',
        name: 'style bistrot classique',
        imageUrl: '/catalogue/table-base-series/TBA-004-01.webp',
        galleryUrls: [
          '/catalogue/table-base-series/TBA-004-02.webp',
          '/catalogue/table-base-series/TBA-004-03.webp',
          '/catalogue/table-base-series/TBA-004-04.webp',
          '/catalogue/table-base-series/TBA-004-05.webp',
          '/catalogue/table-base-series/TBA-004-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Piètement double de table',
      'Structure aluminium',
      'Style bistrot classique',
      'Compatible projets terrasse CHR',
      'Photos groupées par fiche produit',
      'Plateau à sélectionner séparément',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'table-base-tba-005',
    sku: 'TBA-005',
    category: 'table',
    name: 'Piètement de table PROVENCE - style classique',
    description:
      'Piètement de table PROVENCE - style classique pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en piètement aluminium, dimensions 70x70x72 cm, poids 8.5 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Compatible avec projets de plateaux et implantations terrasse en volume.',
    dimensions: {
      l: 70,
      w: 70,
      h: 72,
    },
    cbmPerUnit: 0.055,
    weightKg: 8.5,
    moqUnits: 20,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.65,
    mainImageUrl: '/catalogue/table-base-series/TBA-005-01.webp',
    galleryUrls: [
      '/catalogue/table-base-series/TBA-005-02.webp',
      '/catalogue/table-base-series/TBA-005-03.webp',
      '/catalogue/table-base-series/TBA-005-04.webp',
      '/catalogue/table-base-series/TBA-005-05.webp',
    ],
    variants: [
      {
        id: 'tba-005-design-principal',
        name: 'style bistrot classique',
        imageUrl: '/catalogue/table-base-series/TBA-005-01.webp',
        galleryUrls: [
          '/catalogue/table-base-series/TBA-005-02.webp',
          '/catalogue/table-base-series/TBA-005-03.webp',
          '/catalogue/table-base-series/TBA-005-04.webp',
          '/catalogue/table-base-series/TBA-005-05.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Piètement de table bistrot',
      'Structure aluminium',
      'Style bistrot classique',
      'Compatible projets terrasse CHR',
      'Photos groupées par fiche produit',
      'Plateau à sélectionner séparément',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'table-base-tba-006',
    sku: 'TBA-006',
    category: 'table',
    name: 'Piètement de table CEVENNES - plateau rabattable',
    description:
      'Piètement de table CEVENNES - plateau rabattable pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en piètement aluminium, dimensions 70x70x72 cm, poids 8.5 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Compatible avec projets de plateaux et implantations terrasse en volume.',
    dimensions: {
      l: 70,
      w: 70,
      h: 72,
    },
    cbmPerUnit: 0.055,
    weightKg: 8.5,
    moqUnits: 20,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.65,
    mainImageUrl: '/catalogue/table-base-series/TBA-006-01.webp',
    galleryUrls: [
      '/catalogue/table-base-series/TBA-006-02.webp',
      '/catalogue/table-base-series/TBA-006-03.webp',
      '/catalogue/table-base-series/TBA-006-04.webp',
      '/catalogue/table-base-series/TBA-006-05.webp',
      '/catalogue/table-base-series/TBA-006-06.webp',
    ],
    variants: [
      {
        id: 'tba-006-design-principal',
        name: 'plateau rabattable',
        imageUrl: '/catalogue/table-base-series/TBA-006-01.webp',
        galleryUrls: [
          '/catalogue/table-base-series/TBA-006-02.webp',
          '/catalogue/table-base-series/TBA-006-03.webp',
          '/catalogue/table-base-series/TBA-006-04.webp',
          '/catalogue/table-base-series/TBA-006-05.webp',
          '/catalogue/table-base-series/TBA-006-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Piètement rabattable de table',
      'Structure aluminium',
      'Plateau rabattable',
      'Compatible projets terrasse CHR',
      'Photos groupées par fiche produit',
      'Plateau à sélectionner séparément',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'table-base-tba-007',
    sku: 'TBA-007',
    category: 'table',
    name: 'Piètement de table ALPILLES - plateau rabattable',
    description:
      'Piètement de table ALPILLES - plateau rabattable pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en piètement aluminium, dimensions 70x70x72 cm, poids 8.5 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Compatible avec projets de plateaux et implantations terrasse en volume.',
    dimensions: {
      l: 70,
      w: 70,
      h: 72,
    },
    cbmPerUnit: 0.055,
    weightKg: 8.5,
    moqUnits: 20,
    basePriceHt: 99,
    retailPriceRef: 173,
    ecoContribution: 0.65,
    mainImageUrl: '/catalogue/table-base-series/TBA-007-01.webp',
    galleryUrls: [
      '/catalogue/table-base-series/TBA-007-02.webp',
      '/catalogue/table-base-series/TBA-007-03.webp',
      '/catalogue/table-base-series/TBA-007-04.webp',
      '/catalogue/table-base-series/TBA-007-05.webp',
    ],
    variants: [
      {
        id: 'tba-007-design-principal',
        name: 'plateau rabattable',
        imageUrl: '/catalogue/table-base-series/TBA-007-01.webp',
        galleryUrls: [
          '/catalogue/table-base-series/TBA-007-02.webp',
          '/catalogue/table-base-series/TBA-007-03.webp',
          '/catalogue/table-base-series/TBA-007-04.webp',
          '/catalogue/table-base-series/TBA-007-05.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Piètement rabattable de table',
      'Structure aluminium',
      'Plateau rabattable',
      'Compatible projets terrasse CHR',
      'Photos groupées par fiche produit',
      'Plateau à sélectionner séparément',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
]
