import type { Product } from './products'

// Catalogue textilène anonymisé. Ne contient aucune source fournisseur.
// Photos locales groupées par SKU dans public/catalogue/teslin-series.
export const TESLIN_PRODUCTS: Product[] = [
  {
    id: 'teslin-tes-001',
    sku: 'TES-001',
    category: 'armchair',
    name: 'Fauteuil de terrasse SEVILLE - tressage beige / blanc',
    description:
      'Fauteuil de terrasse SEVILLE - tressage beige / blanc pour terrasse de restaurant, café, hôtel, rooftop et espace CHR premium. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 62x60x82 cm, poids 6.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 62,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 6.2,
    moqUnits: 50,
    basePriceHt: 119,
    retailPriceRef: 208,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/teslin-series/TES-001-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-001-02.webp',
      '/catalogue/teslin-series/TES-001-03.webp',
      '/catalogue/teslin-series/TES-001-04.webp',
      '/catalogue/teslin-series/TES-001-05.webp',
      '/catalogue/teslin-series/TES-001-06.webp',
      '/catalogue/teslin-series/TES-001-07.webp',
      '/catalogue/teslin-series/TES-001-08.webp',
      '/catalogue/teslin-series/TES-001-09.webp',
    ],
    variants: [
      {
        id: 'tes-001-design-principal',
        name: 'tressage textilène beige / blanc',
        imageUrl: '/catalogue/teslin-series/TES-001-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-001-02.webp',
          '/catalogue/teslin-series/TES-001-03.webp',
          '/catalogue/teslin-series/TES-001-04.webp',
          '/catalogue/teslin-series/TES-001-05.webp',
          '/catalogue/teslin-series/TES-001-06.webp',
          '/catalogue/teslin-series/TES-001-07.webp',
          '/catalogue/teslin-series/TES-001-08.webp',
          '/catalogue/teslin-series/TES-001-09.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Fauteuil textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Tressage textilène',
      'Coloris beige / blanc',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-002',
    sku: 'TES-002',
    category: 'chair',
    name: 'Chaise de terrasse VALENCIA - motif géométrique beige',
    description:
      'Chaise de terrasse VALENCIA - motif géométrique beige pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 54x58x84 cm, poids 4.8 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 54,
      w: 58,
      h: 84,
    },
    cbmPerUnit: 0.08,
    weightKg: 4.8,
    moqUnits: 50,
    basePriceHt: 89,
    retailPriceRef: 156,
    ecoContribution: 0.3,
    mainImageUrl: '/catalogue/teslin-series/TES-002-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-002-02.webp',
      '/catalogue/teslin-series/TES-002-03.webp',
      '/catalogue/teslin-series/TES-002-04.webp',
      '/catalogue/teslin-series/TES-002-05.webp',
      '/catalogue/teslin-series/TES-002-06.webp',
      '/catalogue/teslin-series/TES-002-07.webp',
      '/catalogue/teslin-series/TES-002-08.webp',
      '/catalogue/teslin-series/TES-002-09.webp',
    ],
    variants: [
      {
        id: 'tes-002-design-principal',
        name: 'motif géométrique beige',
        imageUrl: '/catalogue/teslin-series/TES-002-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-002-02.webp',
          '/catalogue/teslin-series/TES-002-03.webp',
          '/catalogue/teslin-series/TES-002-04.webp',
          '/catalogue/teslin-series/TES-002-05.webp',
          '/catalogue/teslin-series/TES-002-06.webp',
          '/catalogue/teslin-series/TES-002-07.webp',
          '/catalogue/teslin-series/TES-002-08.webp',
          '/catalogue/teslin-series/TES-002-09.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Motif géométrique',
      'Coloris beige',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-003',
    sku: 'TES-003',
    category: 'table',
    name: 'Ensemble repas terrasse MALAGA - maille textilène noir',
    description:
      'Ensemble repas terrasse MALAGA - maille textilène noir pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 140x80x74 cm, poids 18 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 140,
      w: 80,
      h: 74,
    },
    cbmPerUnit: 0.18,
    weightKg: 18,
    moqUnits: 20,
    basePriceHt: 229,
    retailPriceRef: 401,
    ecoContribution: 0.8,
    mainImageUrl: '/catalogue/teslin-series/TES-003-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-003-02.webp',
      '/catalogue/teslin-series/TES-003-03.webp',
      '/catalogue/teslin-series/TES-003-04.webp',
      '/catalogue/teslin-series/TES-003-05.webp',
      '/catalogue/teslin-series/TES-003-06.webp',
    ],
    variants: [
      {
        id: 'tes-003-design-principal',
        name: 'maille textilène noir',
        imageUrl: '/catalogue/teslin-series/TES-003-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-003-02.webp',
          '/catalogue/teslin-series/TES-003-03.webp',
          '/catalogue/teslin-series/TES-003-04.webp',
          '/catalogue/teslin-series/TES-003-05.webp',
          '/catalogue/teslin-series/TES-003-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Ensemble repas textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Maille textilène',
      'Coloris noir',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-004',
    sku: 'TES-004',
    category: 'bench',
    name: 'Bain de soleil textilène PALMA - maille textilène vert',
    description:
      'Bain de soleil textilène PALMA - maille textilène vert pour zone lounge, piscine, rooftop, camping, hôtel et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 178x66x36 cm, poids 14 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 178,
      w: 66,
      h: 36,
    },
    cbmPerUnit: 0.32,
    weightKg: 14,
    moqUnits: 20,
    basePriceHt: 249,
    retailPriceRef: 436,
    ecoContribution: 1,
    mainImageUrl: '/catalogue/teslin-series/TES-004-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-004-02.webp',
      '/catalogue/teslin-series/TES-004-03.webp',
      '/catalogue/teslin-series/TES-004-04.webp',
      '/catalogue/teslin-series/TES-004-05.webp',
      '/catalogue/teslin-series/TES-004-06.webp',
    ],
    variants: [
      {
        id: 'tes-004-design-principal',
        name: 'maille textilène vert',
        imageUrl: '/catalogue/teslin-series/TES-004-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-004-02.webp',
          '/catalogue/teslin-series/TES-004-03.webp',
          '/catalogue/teslin-series/TES-004-04.webp',
          '/catalogue/teslin-series/TES-004-05.webp',
          '/catalogue/teslin-series/TES-004-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Bain de soleil textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Maille textilène',
      'Coloris vert',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-005',
    sku: 'TES-005',
    category: 'table',
    name: 'Ensemble repas terrasse IBIZA - maille textilène blanc',
    description:
      'Ensemble repas terrasse IBIZA - maille textilène blanc pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 140x80x74 cm, poids 18 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 140,
      w: 80,
      h: 74,
    },
    cbmPerUnit: 0.18,
    weightKg: 18,
    moqUnits: 20,
    basePriceHt: 229,
    retailPriceRef: 401,
    ecoContribution: 0.8,
    mainImageUrl: '/catalogue/teslin-series/TES-005-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-005-02.webp',
      '/catalogue/teslin-series/TES-005-03.webp',
      '/catalogue/teslin-series/TES-005-04.webp',
      '/catalogue/teslin-series/TES-005-05.webp',
      '/catalogue/teslin-series/TES-005-06.webp',
    ],
    variants: [
      {
        id: 'tes-005-design-principal',
        name: 'maille textilène blanc',
        imageUrl: '/catalogue/teslin-series/TES-005-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-005-02.webp',
          '/catalogue/teslin-series/TES-005-03.webp',
          '/catalogue/teslin-series/TES-005-04.webp',
          '/catalogue/teslin-series/TES-005-05.webp',
          '/catalogue/teslin-series/TES-005-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Ensemble repas textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Maille textilène',
      'Coloris blanc',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-006',
    sku: 'TES-006',
    category: 'table',
    name: 'Ensemble repas terrasse CORDOBA - maille textilène blanc',
    description:
      'Ensemble repas terrasse CORDOBA - maille textilène blanc pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 140x80x74 cm, poids 18 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 140,
      w: 80,
      h: 74,
    },
    cbmPerUnit: 0.18,
    weightKg: 18,
    moqUnits: 20,
    basePriceHt: 229,
    retailPriceRef: 401,
    ecoContribution: 0.8,
    mainImageUrl: '/catalogue/teslin-series/TES-006-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-006-02.webp',
      '/catalogue/teslin-series/TES-006-03.webp',
      '/catalogue/teslin-series/TES-006-04.webp',
      '/catalogue/teslin-series/TES-006-05.webp',
      '/catalogue/teslin-series/TES-006-06.webp',
    ],
    variants: [
      {
        id: 'tes-006-design-principal',
        name: 'maille textilène blanc',
        imageUrl: '/catalogue/teslin-series/TES-006-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-006-02.webp',
          '/catalogue/teslin-series/TES-006-03.webp',
          '/catalogue/teslin-series/TES-006-04.webp',
          '/catalogue/teslin-series/TES-006-05.webp',
          '/catalogue/teslin-series/TES-006-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Ensemble repas textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Maille textilène',
      'Coloris blanc',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-007',
    sku: 'TES-007',
    category: 'table',
    name: 'Ensemble repas terrasse GRANADA - maille textilène blanc / noir',
    description:
      'Ensemble repas terrasse GRANADA - maille textilène blanc / noir pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 140x80x74 cm, poids 18 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 140,
      w: 80,
      h: 74,
    },
    cbmPerUnit: 0.18,
    weightKg: 18,
    moqUnits: 20,
    basePriceHt: 229,
    retailPriceRef: 401,
    ecoContribution: 0.8,
    mainImageUrl: '/catalogue/teslin-series/TES-007-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-007-02.webp',
      '/catalogue/teslin-series/TES-007-03.webp',
      '/catalogue/teslin-series/TES-007-04.webp',
      '/catalogue/teslin-series/TES-007-05.webp',
      '/catalogue/teslin-series/TES-007-06.webp',
    ],
    variants: [
      {
        id: 'tes-007-design-principal',
        name: 'maille textilène blanc / noir',
        imageUrl: '/catalogue/teslin-series/TES-007-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-007-02.webp',
          '/catalogue/teslin-series/TES-007-03.webp',
          '/catalogue/teslin-series/TES-007-04.webp',
          '/catalogue/teslin-series/TES-007-05.webp',
          '/catalogue/teslin-series/TES-007-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Ensemble repas textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Maille textilène',
      'Coloris blanc / noir',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-008',
    sku: 'TES-008',
    category: 'table',
    name: 'Ensemble repas terrasse TOLEDO - maille textilène blanc / vert',
    description:
      'Ensemble repas terrasse TOLEDO - maille textilène blanc / vert pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 140x80x74 cm, poids 18 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 140,
      w: 80,
      h: 74,
    },
    cbmPerUnit: 0.18,
    weightKg: 18,
    moqUnits: 20,
    basePriceHt: 229,
    retailPriceRef: 401,
    ecoContribution: 0.8,
    mainImageUrl: '/catalogue/teslin-series/TES-008-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-008-02.webp',
      '/catalogue/teslin-series/TES-008-03.webp',
      '/catalogue/teslin-series/TES-008-04.webp',
      '/catalogue/teslin-series/TES-008-05.webp',
    ],
    variants: [
      {
        id: 'tes-008-design-principal',
        name: 'maille textilène blanc / vert',
        imageUrl: '/catalogue/teslin-series/TES-008-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-008-02.webp',
          '/catalogue/teslin-series/TES-008-03.webp',
          '/catalogue/teslin-series/TES-008-04.webp',
          '/catalogue/teslin-series/TES-008-05.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Ensemble repas textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Maille textilène',
      'Coloris blanc / vert',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-009',
    sku: 'TES-009',
    category: 'table',
    name: 'Ensemble repas terrasse MARBELLA - tressage',
    description:
      'Ensemble repas terrasse MARBELLA - tressage pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 140x80x74 cm, poids 18 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 140,
      w: 80,
      h: 74,
    },
    cbmPerUnit: 0.18,
    weightKg: 18,
    moqUnits: 20,
    basePriceHt: 229,
    retailPriceRef: 401,
    ecoContribution: 0.8,
    mainImageUrl: '/catalogue/teslin-series/TES-009-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-009-02.webp',
      '/catalogue/teslin-series/TES-009-03.webp',
      '/catalogue/teslin-series/TES-009-04.webp',
      '/catalogue/teslin-series/TES-009-05.webp',
    ],
    variants: [
      {
        id: 'tes-009-design-principal',
        name: 'tressage textilène',
        imageUrl: '/catalogue/teslin-series/TES-009-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-009-02.webp',
          '/catalogue/teslin-series/TES-009-03.webp',
          '/catalogue/teslin-series/TES-009-04.webp',
          '/catalogue/teslin-series/TES-009-05.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Ensemble repas textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Tressage textilène',
      'Design à valider',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-010',
    sku: 'TES-010',
    category: 'armchair',
    name: 'Fauteuil de terrasse RONDA - blanc / bleu',
    description:
      'Fauteuil de terrasse RONDA - blanc / bleu pour terrasse de restaurant, café, hôtel, rooftop et espace CHR premium. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 62x60x82 cm, poids 6.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 62,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 6.2,
    moqUnits: 50,
    basePriceHt: 119,
    retailPriceRef: 208,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/teslin-series/TES-010-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-010-02.webp',
      '/catalogue/teslin-series/TES-010-03.webp',
      '/catalogue/teslin-series/TES-010-04.webp',
      '/catalogue/teslin-series/TES-010-05.webp',
      '/catalogue/teslin-series/TES-010-06.webp',
      '/catalogue/teslin-series/TES-010-07.webp',
      '/catalogue/teslin-series/TES-010-08.webp',
    ],
    variants: [
      {
        id: 'tes-010-design-principal',
        name: 'motif pied-de-poule blanc / bleu',
        imageUrl: '/catalogue/teslin-series/TES-010-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-010-02.webp',
          '/catalogue/teslin-series/TES-010-03.webp',
          '/catalogue/teslin-series/TES-010-04.webp',
          '/catalogue/teslin-series/TES-010-05.webp',
          '/catalogue/teslin-series/TES-010-06.webp',
          '/catalogue/teslin-series/TES-010-07.webp',
          '/catalogue/teslin-series/TES-010-08.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Fauteuil textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Motif pied-de-poule',
      'Coloris blanc / bleu',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-011',
    sku: 'TES-011',
    category: 'armchair',
    name: 'Fauteuil de terrasse ATHENES - tressage beige / gris',
    description:
      'Fauteuil de terrasse ATHENES - tressage beige / gris pour terrasse de restaurant, café, hôtel, rooftop et espace CHR premium. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 62x60x82 cm, poids 6.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 62,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 6.2,
    moqUnits: 50,
    basePriceHt: 119,
    retailPriceRef: 208,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/teslin-series/TES-011-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-011-02.webp',
      '/catalogue/teslin-series/TES-011-03.webp',
      '/catalogue/teslin-series/TES-011-04.webp',
      '/catalogue/teslin-series/TES-011-05.webp',
      '/catalogue/teslin-series/TES-011-06.webp',
      '/catalogue/teslin-series/TES-011-07.webp',
      '/catalogue/teslin-series/TES-011-08.webp',
    ],
    variants: [
      {
        id: 'tes-011-design-principal',
        name: 'tressage textilène beige / gris',
        imageUrl: '/catalogue/teslin-series/TES-011-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-011-02.webp',
          '/catalogue/teslin-series/TES-011-03.webp',
          '/catalogue/teslin-series/TES-011-04.webp',
          '/catalogue/teslin-series/TES-011-05.webp',
          '/catalogue/teslin-series/TES-011-06.webp',
          '/catalogue/teslin-series/TES-011-07.webp',
          '/catalogue/teslin-series/TES-011-08.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Fauteuil textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Tressage textilène',
      'Coloris beige / gris',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-012',
    sku: 'TES-012',
    category: 'chair',
    name: 'Chaise de terrasse PAROS - tressage blanc / noir',
    description:
      'Chaise de terrasse PAROS - tressage blanc / noir pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 54x58x84 cm, poids 4.8 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 54,
      w: 58,
      h: 84,
    },
    cbmPerUnit: 0.08,
    weightKg: 4.8,
    moqUnits: 50,
    basePriceHt: 89,
    retailPriceRef: 156,
    ecoContribution: 0.3,
    mainImageUrl: '/catalogue/teslin-series/TES-012-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-012-02.webp',
      '/catalogue/teslin-series/TES-012-03.webp',
      '/catalogue/teslin-series/TES-012-04.webp',
      '/catalogue/teslin-series/TES-012-05.webp',
      '/catalogue/teslin-series/TES-012-06.webp',
      '/catalogue/teslin-series/TES-012-07.webp',
      '/catalogue/teslin-series/TES-012-08.webp',
      '/catalogue/teslin-series/TES-012-09.webp',
    ],
    variants: [
      {
        id: 'tes-012-design-principal',
        name: 'tressage textilène blanc / noir',
        imageUrl: '/catalogue/teslin-series/TES-012-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-012-02.webp',
          '/catalogue/teslin-series/TES-012-03.webp',
          '/catalogue/teslin-series/TES-012-04.webp',
          '/catalogue/teslin-series/TES-012-05.webp',
          '/catalogue/teslin-series/TES-012-06.webp',
          '/catalogue/teslin-series/TES-012-07.webp',
          '/catalogue/teslin-series/TES-012-08.webp',
          '/catalogue/teslin-series/TES-012-09.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Tressage textilène',
      'Coloris blanc / noir',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-013',
    sku: 'TES-013',
    category: 'chair',
    name: 'Chaise de terrasse NAXOS - motif géométrique vert',
    description:
      'Chaise de terrasse NAXOS - motif géométrique vert pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 54x58x84 cm, poids 4.8 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 54,
      w: 58,
      h: 84,
    },
    cbmPerUnit: 0.08,
    weightKg: 4.8,
    moqUnits: 50,
    basePriceHt: 89,
    retailPriceRef: 156,
    ecoContribution: 0.3,
    mainImageUrl: '/catalogue/teslin-series/TES-013-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-013-02.webp',
      '/catalogue/teslin-series/TES-013-03.webp',
      '/catalogue/teslin-series/TES-013-04.webp',
      '/catalogue/teslin-series/TES-013-05.webp',
      '/catalogue/teslin-series/TES-013-06.webp',
      '/catalogue/teslin-series/TES-013-07.webp',
      '/catalogue/teslin-series/TES-013-08.webp',
      '/catalogue/teslin-series/TES-013-09.webp',
    ],
    variants: [
      {
        id: 'tes-013-design-principal',
        name: 'motif géométrique vert',
        imageUrl: '/catalogue/teslin-series/TES-013-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-013-02.webp',
          '/catalogue/teslin-series/TES-013-03.webp',
          '/catalogue/teslin-series/TES-013-04.webp',
          '/catalogue/teslin-series/TES-013-05.webp',
          '/catalogue/teslin-series/TES-013-06.webp',
          '/catalogue/teslin-series/TES-013-07.webp',
          '/catalogue/teslin-series/TES-013-08.webp',
          '/catalogue/teslin-series/TES-013-09.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Motif géométrique',
      'Coloris vert',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-014',
    sku: 'TES-014',
    category: 'bench',
    name: 'Bain de soleil textilène HYDRA - tressage beige',
    description:
      'Bain de soleil textilène HYDRA - tressage beige pour zone lounge, piscine, rooftop, camping, hôtel et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 178x66x36 cm, poids 14 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 178,
      w: 66,
      h: 36,
    },
    cbmPerUnit: 0.32,
    weightKg: 14,
    moqUnits: 20,
    basePriceHt: 249,
    retailPriceRef: 436,
    ecoContribution: 1,
    mainImageUrl: '/catalogue/teslin-series/TES-014-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-014-02.webp',
      '/catalogue/teslin-series/TES-014-03.webp',
      '/catalogue/teslin-series/TES-014-04.webp',
      '/catalogue/teslin-series/TES-014-05.webp',
      '/catalogue/teslin-series/TES-014-06.webp',
    ],
    variants: [
      {
        id: 'tes-014-design-principal',
        name: 'tressage textilène beige',
        imageUrl: '/catalogue/teslin-series/TES-014-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-014-02.webp',
          '/catalogue/teslin-series/TES-014-03.webp',
          '/catalogue/teslin-series/TES-014-04.webp',
          '/catalogue/teslin-series/TES-014-05.webp',
          '/catalogue/teslin-series/TES-014-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Bain de soleil textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Tressage textilène',
      'Coloris beige',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-015',
    sku: 'TES-015',
    category: 'bench',
    name: 'Bain de soleil textilène CORFOU - tressage',
    description:
      'Bain de soleil textilène CORFOU - tressage pour zone lounge, piscine, rooftop, camping, hôtel et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 178x66x36 cm, poids 14 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 178,
      w: 66,
      h: 36,
    },
    cbmPerUnit: 0.32,
    weightKg: 14,
    moqUnits: 20,
    basePriceHt: 249,
    retailPriceRef: 436,
    ecoContribution: 1,
    mainImageUrl: '/catalogue/teslin-series/TES-015-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-015-02.webp',
      '/catalogue/teslin-series/TES-015-03.webp',
      '/catalogue/teslin-series/TES-015-04.webp',
      '/catalogue/teslin-series/TES-015-05.webp',
      '/catalogue/teslin-series/TES-015-06.webp',
    ],
    variants: [
      {
        id: 'tes-015-design-principal',
        name: 'tressage textilène',
        imageUrl: '/catalogue/teslin-series/TES-015-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-015-02.webp',
          '/catalogue/teslin-series/TES-015-03.webp',
          '/catalogue/teslin-series/TES-015-04.webp',
          '/catalogue/teslin-series/TES-015-05.webp',
          '/catalogue/teslin-series/TES-015-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Bain de soleil textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Tressage textilène',
      'Design à valider',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-016',
    sku: 'TES-016',
    category: 'chair',
    name: 'Chaise de terrasse MYKONOS - tressage',
    description:
      'Chaise de terrasse MYKONOS - tressage pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 54x58x84 cm, poids 4.8 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 54,
      w: 58,
      h: 84,
    },
    cbmPerUnit: 0.08,
    weightKg: 4.8,
    moqUnits: 50,
    basePriceHt: 89,
    retailPriceRef: 156,
    ecoContribution: 0.3,
    mainImageUrl: '/catalogue/teslin-series/TES-016-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-016-02.webp',
      '/catalogue/teslin-series/TES-016-03.webp',
      '/catalogue/teslin-series/TES-016-04.webp',
      '/catalogue/teslin-series/TES-016-05.webp',
      '/catalogue/teslin-series/TES-016-06.webp',
      '/catalogue/teslin-series/TES-016-07.webp',
      '/catalogue/teslin-series/TES-016-08.webp',
      '/catalogue/teslin-series/TES-016-09.webp',
      '/catalogue/teslin-series/TES-016-10.webp',
    ],
    variants: [
      {
        id: 'tes-016-design-principal',
        name: 'tressage textilène',
        imageUrl: '/catalogue/teslin-series/TES-016-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-016-02.webp',
          '/catalogue/teslin-series/TES-016-03.webp',
          '/catalogue/teslin-series/TES-016-04.webp',
          '/catalogue/teslin-series/TES-016-05.webp',
          '/catalogue/teslin-series/TES-016-06.webp',
          '/catalogue/teslin-series/TES-016-07.webp',
          '/catalogue/teslin-series/TES-016-08.webp',
          '/catalogue/teslin-series/TES-016-09.webp',
          '/catalogue/teslin-series/TES-016-10.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Tressage textilène',
      'Design à valider',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-017',
    sku: 'TES-017',
    category: 'chair',
    name: 'Chaise de terrasse SANTORIN - tressage',
    description:
      'Chaise de terrasse SANTORIN - tressage pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 54x58x84 cm, poids 4.8 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 54,
      w: 58,
      h: 84,
    },
    cbmPerUnit: 0.08,
    weightKg: 4.8,
    moqUnits: 50,
    basePriceHt: 89,
    retailPriceRef: 156,
    ecoContribution: 0.3,
    mainImageUrl: '/catalogue/teslin-series/TES-017-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-017-02.webp',
      '/catalogue/teslin-series/TES-017-03.webp',
      '/catalogue/teslin-series/TES-017-04.webp',
      '/catalogue/teslin-series/TES-017-05.webp',
      '/catalogue/teslin-series/TES-017-06.webp',
    ],
    variants: [
      {
        id: 'tes-017-design-principal',
        name: 'tressage textilène',
        imageUrl: '/catalogue/teslin-series/TES-017-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-017-02.webp',
          '/catalogue/teslin-series/TES-017-03.webp',
          '/catalogue/teslin-series/TES-017-04.webp',
          '/catalogue/teslin-series/TES-017-05.webp',
          '/catalogue/teslin-series/TES-017-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Tressage textilène',
      'Design à valider',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-018',
    sku: 'TES-018',
    category: 'armchair',
    name: 'Fauteuil de terrasse MILOS - maille textilène',
    description:
      'Fauteuil de terrasse MILOS - maille textilène pour terrasse de restaurant, café, hôtel, rooftop et espace CHR premium. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 62x60x82 cm, poids 6.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 62,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 6.2,
    moqUnits: 50,
    basePriceHt: 119,
    retailPriceRef: 208,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/teslin-series/TES-018-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-018-02.webp',
      '/catalogue/teslin-series/TES-018-03.webp',
      '/catalogue/teslin-series/TES-018-04.webp',
      '/catalogue/teslin-series/TES-018-05.webp',
      '/catalogue/teslin-series/TES-018-06.webp',
    ],
    variants: [
      {
        id: 'tes-018-design-principal',
        name: 'maille textilène',
        imageUrl: '/catalogue/teslin-series/TES-018-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-018-02.webp',
          '/catalogue/teslin-series/TES-018-03.webp',
          '/catalogue/teslin-series/TES-018-04.webp',
          '/catalogue/teslin-series/TES-018-05.webp',
          '/catalogue/teslin-series/TES-018-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Fauteuil textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Maille textilène',
      'Design à valider',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-019',
    sku: 'TES-019',
    category: 'chair',
    name: 'Chaise de terrasse RHODES - tressage',
    description:
      'Chaise de terrasse RHODES - tressage pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 54x58x84 cm, poids 4.8 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 54,
      w: 58,
      h: 84,
    },
    cbmPerUnit: 0.08,
    weightKg: 4.8,
    moqUnits: 50,
    basePriceHt: 89,
    retailPriceRef: 156,
    ecoContribution: 0.3,
    mainImageUrl: '/catalogue/teslin-series/TES-019-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-019-02.webp',
      '/catalogue/teslin-series/TES-019-03.webp',
      '/catalogue/teslin-series/TES-019-04.webp',
      '/catalogue/teslin-series/TES-019-05.webp',
      '/catalogue/teslin-series/TES-019-06.webp',
      '/catalogue/teslin-series/TES-019-07.webp',
      '/catalogue/teslin-series/TES-019-08.webp',
    ],
    variants: [
      {
        id: 'tes-019-design-principal',
        name: 'tressage textilène',
        imageUrl: '/catalogue/teslin-series/TES-019-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-019-02.webp',
          '/catalogue/teslin-series/TES-019-03.webp',
          '/catalogue/teslin-series/TES-019-04.webp',
          '/catalogue/teslin-series/TES-019-05.webp',
          '/catalogue/teslin-series/TES-019-06.webp',
          '/catalogue/teslin-series/TES-019-07.webp',
          '/catalogue/teslin-series/TES-019-08.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Tressage textilène',
      'Design à valider',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-020',
    sku: 'TES-020',
    category: 'armchair',
    name: 'Fauteuil de terrasse PATMOS - maille textilène noir',
    description:
      'Fauteuil de terrasse PATMOS - maille textilène noir pour terrasse de restaurant, café, hôtel, rooftop et espace CHR premium. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 62x60x82 cm, poids 6.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 62,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 6.2,
    moqUnits: 50,
    basePriceHt: 119,
    retailPriceRef: 208,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/teslin-series/TES-020-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-020-02.webp',
      '/catalogue/teslin-series/TES-020-03.webp',
      '/catalogue/teslin-series/TES-020-04.webp',
      '/catalogue/teslin-series/TES-020-05.webp',
      '/catalogue/teslin-series/TES-020-06.webp',
    ],
    variants: [
      {
        id: 'tes-020-design-principal',
        name: 'maille textilène noir',
        imageUrl: '/catalogue/teslin-series/TES-020-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-020-02.webp',
          '/catalogue/teslin-series/TES-020-03.webp',
          '/catalogue/teslin-series/TES-020-04.webp',
          '/catalogue/teslin-series/TES-020-05.webp',
          '/catalogue/teslin-series/TES-020-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Fauteuil textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Maille textilène',
      'Coloris noir',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-021',
    sku: 'TES-021',
    category: 'chair',
    name: 'Chaise de terrasse ATLAS - tressage vert',
    description:
      'Chaise de terrasse ATLAS - tressage vert pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 54x58x84 cm, poids 4.8 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 54,
      w: 58,
      h: 84,
    },
    cbmPerUnit: 0.08,
    weightKg: 4.8,
    moqUnits: 50,
    basePriceHt: 89,
    retailPriceRef: 156,
    ecoContribution: 0.3,
    mainImageUrl: '/catalogue/teslin-series/TES-021-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-021-02.webp',
      '/catalogue/teslin-series/TES-021-03.webp',
      '/catalogue/teslin-series/TES-021-04.webp',
      '/catalogue/teslin-series/TES-021-05.webp',
      '/catalogue/teslin-series/TES-021-06.webp',
      '/catalogue/teslin-series/TES-021-07.webp',
      '/catalogue/teslin-series/TES-021-08.webp',
    ],
    variants: [
      {
        id: 'tes-021-design-principal',
        name: 'tressage textilène vert',
        imageUrl: '/catalogue/teslin-series/TES-021-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-021-02.webp',
          '/catalogue/teslin-series/TES-021-03.webp',
          '/catalogue/teslin-series/TES-021-04.webp',
          '/catalogue/teslin-series/TES-021-05.webp',
          '/catalogue/teslin-series/TES-021-06.webp',
          '/catalogue/teslin-series/TES-021-07.webp',
          '/catalogue/teslin-series/TES-021-08.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Tressage textilène',
      'Coloris vert',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-022',
    sku: 'TES-022',
    category: 'chair',
    name: 'Chaise de terrasse MEDINA - chevron blanc / noir / brun',
    description:
      'Chaise de terrasse MEDINA - chevron blanc / noir / brun pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 54x58x84 cm, poids 4.8 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 54,
      w: 58,
      h: 84,
    },
    cbmPerUnit: 0.08,
    weightKg: 4.8,
    moqUnits: 50,
    basePriceHt: 89,
    retailPriceRef: 156,
    ecoContribution: 0.3,
    mainImageUrl: '/catalogue/teslin-series/TES-022-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-022-02.webp',
      '/catalogue/teslin-series/TES-022-03.webp',
      '/catalogue/teslin-series/TES-022-04.webp',
      '/catalogue/teslin-series/TES-022-05.webp',
      '/catalogue/teslin-series/TES-022-06.webp',
      '/catalogue/teslin-series/TES-022-07.webp',
      '/catalogue/teslin-series/TES-022-08.webp',
      '/catalogue/teslin-series/TES-022-09.webp',
    ],
    variants: [
      {
        id: 'tes-022-design-principal',
        name: 'motif chevron blanc / noir / brun',
        imageUrl: '/catalogue/teslin-series/TES-022-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-022-02.webp',
          '/catalogue/teslin-series/TES-022-03.webp',
          '/catalogue/teslin-series/TES-022-04.webp',
          '/catalogue/teslin-series/TES-022-05.webp',
          '/catalogue/teslin-series/TES-022-06.webp',
          '/catalogue/teslin-series/TES-022-07.webp',
          '/catalogue/teslin-series/TES-022-08.webp',
          '/catalogue/teslin-series/TES-022-09.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Motif chevron',
      'Coloris blanc / noir / brun',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-023',
    sku: 'TES-023',
    category: 'armchair',
    name: 'Fauteuil de terrasse OASIS - motif géométrique blanc / vert',
    description:
      'Fauteuil de terrasse OASIS - motif géométrique blanc / vert pour terrasse de restaurant, café, hôtel, rooftop et espace CHR premium. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 62x60x82 cm, poids 6.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 62,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 6.2,
    moqUnits: 50,
    basePriceHt: 119,
    retailPriceRef: 208,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/teslin-series/TES-023-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-023-02.webp',
      '/catalogue/teslin-series/TES-023-03.webp',
      '/catalogue/teslin-series/TES-023-04.webp',
      '/catalogue/teslin-series/TES-023-05.webp',
      '/catalogue/teslin-series/TES-023-06.webp',
      '/catalogue/teslin-series/TES-023-07.webp',
      '/catalogue/teslin-series/TES-023-08.webp',
      '/catalogue/teslin-series/TES-023-09.webp',
    ],
    variants: [
      {
        id: 'tes-023-design-principal',
        name: 'motif géométrique blanc / vert',
        imageUrl: '/catalogue/teslin-series/TES-023-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-023-02.webp',
          '/catalogue/teslin-series/TES-023-03.webp',
          '/catalogue/teslin-series/TES-023-04.webp',
          '/catalogue/teslin-series/TES-023-05.webp',
          '/catalogue/teslin-series/TES-023-06.webp',
          '/catalogue/teslin-series/TES-023-07.webp',
          '/catalogue/teslin-series/TES-023-08.webp',
          '/catalogue/teslin-series/TES-023-09.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Fauteuil textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Motif géométrique',
      'Coloris blanc / vert',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-024',
    sku: 'TES-024',
    category: 'chair',
    name: 'Chaise haute terrasse RIVAGE - chevron brun',
    description:
      'Chaise haute terrasse RIVAGE - chevron brun pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 62x60x108 cm, poids 6.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 62,
      w: 60,
      h: 108,
    },
    cbmPerUnit: 0.1,
    weightKg: 6.2,
    moqUnits: 50,
    basePriceHt: 119,
    retailPriceRef: 208,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/teslin-series/TES-024-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-024-02.webp',
      '/catalogue/teslin-series/TES-024-03.webp',
      '/catalogue/teslin-series/TES-024-04.webp',
      '/catalogue/teslin-series/TES-024-05.webp',
      '/catalogue/teslin-series/TES-024-06.webp',
      '/catalogue/teslin-series/TES-024-07.webp',
      '/catalogue/teslin-series/TES-024-08.webp',
    ],
    variants: [
      {
        id: 'tes-024-design-principal',
        name: 'motif chevron brun',
        imageUrl: '/catalogue/teslin-series/TES-024-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-024-02.webp',
          '/catalogue/teslin-series/TES-024-03.webp',
          '/catalogue/teslin-series/TES-024-04.webp',
          '/catalogue/teslin-series/TES-024-05.webp',
          '/catalogue/teslin-series/TES-024-06.webp',
          '/catalogue/teslin-series/TES-024-07.webp',
          '/catalogue/teslin-series/TES-024-08.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise haute textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Motif chevron',
      'Coloris brun',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-025',
    sku: 'TES-025',
    category: 'table',
    name: 'Ensemble repas terrasse CALANQUE - maille textilène blanc / bleu',
    description:
      'Ensemble repas terrasse CALANQUE - maille textilène blanc / bleu pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 140x80x74 cm, poids 18 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 140,
      w: 80,
      h: 74,
    },
    cbmPerUnit: 0.18,
    weightKg: 18,
    moqUnits: 20,
    basePriceHt: 229,
    retailPriceRef: 401,
    ecoContribution: 0.8,
    mainImageUrl: '/catalogue/teslin-series/TES-025-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-025-02.webp',
      '/catalogue/teslin-series/TES-025-03.webp',
      '/catalogue/teslin-series/TES-025-04.webp',
      '/catalogue/teslin-series/TES-025-05.webp',
      '/catalogue/teslin-series/TES-025-06.webp',
    ],
    variants: [
      {
        id: 'tes-025-design-principal',
        name: 'maille textilène blanc / bleu',
        imageUrl: '/catalogue/teslin-series/TES-025-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-025-02.webp',
          '/catalogue/teslin-series/TES-025-03.webp',
          '/catalogue/teslin-series/TES-025-04.webp',
          '/catalogue/teslin-series/TES-025-05.webp',
          '/catalogue/teslin-series/TES-025-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Ensemble repas textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Maille textilène',
      'Coloris blanc / bleu',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-026',
    sku: 'TES-026',
    category: 'chair',
    name: 'Chaise de terrasse AZUR - maille textilène blanc / bleu',
    description:
      'Chaise de terrasse AZUR - maille textilène blanc / bleu pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 54x58x84 cm, poids 4.8 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 54,
      w: 58,
      h: 84,
    },
    cbmPerUnit: 0.08,
    weightKg: 4.8,
    moqUnits: 50,
    basePriceHt: 89,
    retailPriceRef: 156,
    ecoContribution: 0.3,
    mainImageUrl: '/catalogue/teslin-series/TES-026-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-026-02.webp',
      '/catalogue/teslin-series/TES-026-03.webp',
      '/catalogue/teslin-series/TES-026-04.webp',
      '/catalogue/teslin-series/TES-026-05.webp',
      '/catalogue/teslin-series/TES-026-06.webp',
      '/catalogue/teslin-series/TES-026-07.webp',
      '/catalogue/teslin-series/TES-026-08.webp',
      '/catalogue/teslin-series/TES-026-09.webp',
    ],
    variants: [
      {
        id: 'tes-026-design-principal',
        name: 'maille textilène blanc / bleu',
        imageUrl: '/catalogue/teslin-series/TES-026-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-026-02.webp',
          '/catalogue/teslin-series/TES-026-03.webp',
          '/catalogue/teslin-series/TES-026-04.webp',
          '/catalogue/teslin-series/TES-026-05.webp',
          '/catalogue/teslin-series/TES-026-06.webp',
          '/catalogue/teslin-series/TES-026-07.webp',
          '/catalogue/teslin-series/TES-026-08.webp',
          '/catalogue/teslin-series/TES-026-09.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Maille textilène',
      'Coloris blanc / bleu',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-027',
    sku: 'TES-027',
    category: 'armchair',
    name: 'Fauteuil de terrasse ESTEREL - tressage beige',
    description:
      'Fauteuil de terrasse ESTEREL - tressage beige pour terrasse de restaurant, café, hôtel, rooftop et espace CHR premium. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 62x60x82 cm, poids 6.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 62,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 6.2,
    moqUnits: 50,
    basePriceHt: 119,
    retailPriceRef: 208,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/teslin-series/TES-027-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-027-02.webp',
      '/catalogue/teslin-series/TES-027-03.webp',
      '/catalogue/teslin-series/TES-027-04.webp',
      '/catalogue/teslin-series/TES-027-05.webp',
      '/catalogue/teslin-series/TES-027-06.webp',
      '/catalogue/teslin-series/TES-027-07.webp',
      '/catalogue/teslin-series/TES-027-08.webp',
      '/catalogue/teslin-series/TES-027-09.webp',
    ],
    variants: [
      {
        id: 'tes-027-design-principal',
        name: 'tressage textilène beige',
        imageUrl: '/catalogue/teslin-series/TES-027-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-027-02.webp',
          '/catalogue/teslin-series/TES-027-03.webp',
          '/catalogue/teslin-series/TES-027-04.webp',
          '/catalogue/teslin-series/TES-027-05.webp',
          '/catalogue/teslin-series/TES-027-06.webp',
          '/catalogue/teslin-series/TES-027-07.webp',
          '/catalogue/teslin-series/TES-027-08.webp',
          '/catalogue/teslin-series/TES-027-09.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Fauteuil textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Tressage textilène',
      'Coloris beige',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-028',
    sku: 'TES-028',
    category: 'armchair',
    name: 'Fauteuil de terrasse LUBERON - maille textilène gris',
    description:
      'Fauteuil de terrasse LUBERON - maille textilène gris pour terrasse de restaurant, café, hôtel, rooftop et espace CHR premium. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 62x60x82 cm, poids 6.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 62,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 6.2,
    moqUnits: 50,
    basePriceHt: 119,
    retailPriceRef: 208,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/teslin-series/TES-028-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-028-02.webp',
      '/catalogue/teslin-series/TES-028-03.webp',
      '/catalogue/teslin-series/TES-028-04.webp',
      '/catalogue/teslin-series/TES-028-05.webp',
      '/catalogue/teslin-series/TES-028-06.webp',
      '/catalogue/teslin-series/TES-028-07.webp',
      '/catalogue/teslin-series/TES-028-08.webp',
      '/catalogue/teslin-series/TES-028-09.webp',
    ],
    variants: [
      {
        id: 'tes-028-design-principal',
        name: 'maille textilène gris',
        imageUrl: '/catalogue/teslin-series/TES-028-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-028-02.webp',
          '/catalogue/teslin-series/TES-028-03.webp',
          '/catalogue/teslin-series/TES-028-04.webp',
          '/catalogue/teslin-series/TES-028-05.webp',
          '/catalogue/teslin-series/TES-028-06.webp',
          '/catalogue/teslin-series/TES-028-07.webp',
          '/catalogue/teslin-series/TES-028-08.webp',
          '/catalogue/teslin-series/TES-028-09.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Fauteuil textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Maille textilène',
      'Coloris gris',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-029',
    sku: 'TES-029',
    category: 'chair',
    name: 'Chaise de terrasse CAMARGUE - maille textilène beige / noir',
    description:
      'Chaise de terrasse CAMARGUE - maille textilène beige / noir pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 54x58x84 cm, poids 4.8 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 54,
      w: 58,
      h: 84,
    },
    cbmPerUnit: 0.08,
    weightKg: 4.8,
    moqUnits: 50,
    basePriceHt: 89,
    retailPriceRef: 156,
    ecoContribution: 0.3,
    mainImageUrl: '/catalogue/teslin-series/TES-029-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-029-02.webp',
      '/catalogue/teslin-series/TES-029-03.webp',
      '/catalogue/teslin-series/TES-029-04.webp',
      '/catalogue/teslin-series/TES-029-05.webp',
      '/catalogue/teslin-series/TES-029-06.webp',
      '/catalogue/teslin-series/TES-029-07.webp',
      '/catalogue/teslin-series/TES-029-08.webp',
      '/catalogue/teslin-series/TES-029-09.webp',
    ],
    variants: [
      {
        id: 'tes-029-design-principal',
        name: 'maille textilène beige / noir',
        imageUrl: '/catalogue/teslin-series/TES-029-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-029-02.webp',
          '/catalogue/teslin-series/TES-029-03.webp',
          '/catalogue/teslin-series/TES-029-04.webp',
          '/catalogue/teslin-series/TES-029-05.webp',
          '/catalogue/teslin-series/TES-029-06.webp',
          '/catalogue/teslin-series/TES-029-07.webp',
          '/catalogue/teslin-series/TES-029-08.webp',
          '/catalogue/teslin-series/TES-029-09.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Maille textilène',
      'Coloris beige / noir',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-030',
    sku: 'TES-030',
    category: 'chair',
    name: 'Chaise de terrasse PROVENCE - maille textilène',
    description:
      'Chaise de terrasse PROVENCE - maille textilène pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 54x58x84 cm, poids 4.8 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 54,
      w: 58,
      h: 84,
    },
    cbmPerUnit: 0.08,
    weightKg: 4.8,
    moqUnits: 50,
    basePriceHt: 89,
    retailPriceRef: 156,
    ecoContribution: 0.3,
    mainImageUrl: '/catalogue/teslin-series/TES-030-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-030-02.webp',
      '/catalogue/teslin-series/TES-030-03.webp',
      '/catalogue/teslin-series/TES-030-04.webp',
      '/catalogue/teslin-series/TES-030-05.webp',
      '/catalogue/teslin-series/TES-030-06.webp',
    ],
    variants: [
      {
        id: 'tes-030-design-principal',
        name: 'maille textilène',
        imageUrl: '/catalogue/teslin-series/TES-030-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-030-02.webp',
          '/catalogue/teslin-series/TES-030-03.webp',
          '/catalogue/teslin-series/TES-030-04.webp',
          '/catalogue/teslin-series/TES-030-05.webp',
          '/catalogue/teslin-series/TES-030-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Maille textilène',
      'Design à valider',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-031',
    sku: 'TES-031',
    category: 'table',
    name: 'Ensemble repas terrasse CEVENNES - maille textilène',
    description:
      'Ensemble repas terrasse CEVENNES - maille textilène pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 140x80x74 cm, poids 18 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 140,
      w: 80,
      h: 74,
    },
    cbmPerUnit: 0.18,
    weightKg: 18,
    moqUnits: 20,
    basePriceHt: 229,
    retailPriceRef: 401,
    ecoContribution: 0.8,
    mainImageUrl: '/catalogue/teslin-series/TES-031-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-031-02.webp',
      '/catalogue/teslin-series/TES-031-03.webp',
      '/catalogue/teslin-series/TES-031-04.webp',
      '/catalogue/teslin-series/TES-031-05.webp',
      '/catalogue/teslin-series/TES-031-06.webp',
    ],
    variants: [
      {
        id: 'tes-031-design-principal',
        name: 'maille textilène',
        imageUrl: '/catalogue/teslin-series/TES-031-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-031-02.webp',
          '/catalogue/teslin-series/TES-031-03.webp',
          '/catalogue/teslin-series/TES-031-04.webp',
          '/catalogue/teslin-series/TES-031-05.webp',
          '/catalogue/teslin-series/TES-031-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Ensemble repas textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Maille textilène',
      'Design à valider',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-032',
    sku: 'TES-032',
    category: 'armchair',
    name: 'Fauteuil de terrasse ALPILLES - tressage rouge',
    description:
      'Fauteuil de terrasse ALPILLES - tressage rouge pour terrasse de restaurant, café, hôtel, rooftop et espace CHR premium. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 62x60x82 cm, poids 6.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 62,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 6.2,
    moqUnits: 50,
    basePriceHt: 119,
    retailPriceRef: 208,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/teslin-series/TES-032-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-032-02.webp',
      '/catalogue/teslin-series/TES-032-03.webp',
      '/catalogue/teslin-series/TES-032-04.webp',
      '/catalogue/teslin-series/TES-032-05.webp',
      '/catalogue/teslin-series/TES-032-06.webp',
    ],
    variants: [
      {
        id: 'tes-032-design-principal',
        name: 'tressage textilène rouge',
        imageUrl: '/catalogue/teslin-series/TES-032-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-032-02.webp',
          '/catalogue/teslin-series/TES-032-03.webp',
          '/catalogue/teslin-series/TES-032-04.webp',
          '/catalogue/teslin-series/TES-032-05.webp',
          '/catalogue/teslin-series/TES-032-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Fauteuil textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Tressage textilène',
      'Coloris rouge',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-033',
    sku: 'TES-033',
    category: 'chair',
    name: 'Chaise de terrasse GARONNE - tressage',
    description:
      'Chaise de terrasse GARONNE - tressage pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 54x58x84 cm, poids 4.8 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 54,
      w: 58,
      h: 84,
    },
    cbmPerUnit: 0.08,
    weightKg: 4.8,
    moqUnits: 50,
    basePriceHt: 89,
    retailPriceRef: 156,
    ecoContribution: 0.3,
    mainImageUrl: '/catalogue/teslin-series/TES-033-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-033-02.webp',
      '/catalogue/teslin-series/TES-033-03.webp',
      '/catalogue/teslin-series/TES-033-04.webp',
      '/catalogue/teslin-series/TES-033-05.webp',
      '/catalogue/teslin-series/TES-033-06.webp',
    ],
    variants: [
      {
        id: 'tes-033-design-principal',
        name: 'tressage textilène',
        imageUrl: '/catalogue/teslin-series/TES-033-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-033-02.webp',
          '/catalogue/teslin-series/TES-033-03.webp',
          '/catalogue/teslin-series/TES-033-04.webp',
          '/catalogue/teslin-series/TES-033-05.webp',
          '/catalogue/teslin-series/TES-033-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Tressage textilène',
      'Design à valider',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-034',
    sku: 'TES-034',
    category: 'table',
    name: 'Ensemble repas terrasse LOIRE - maille textilène',
    description:
      'Ensemble repas terrasse LOIRE - maille textilène pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 140x80x74 cm, poids 18 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 140,
      w: 80,
      h: 74,
    },
    cbmPerUnit: 0.18,
    weightKg: 18,
    moqUnits: 20,
    basePriceHt: 229,
    retailPriceRef: 401,
    ecoContribution: 0.8,
    mainImageUrl: '/catalogue/teslin-series/TES-034-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-034-02.webp',
      '/catalogue/teslin-series/TES-034-03.webp',
      '/catalogue/teslin-series/TES-034-04.webp',
      '/catalogue/teslin-series/TES-034-05.webp',
      '/catalogue/teslin-series/TES-034-06.webp',
      '/catalogue/teslin-series/TES-034-07.webp',
    ],
    variants: [
      {
        id: 'tes-034-design-principal',
        name: 'maille textilène',
        imageUrl: '/catalogue/teslin-series/TES-034-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-034-02.webp',
          '/catalogue/teslin-series/TES-034-03.webp',
          '/catalogue/teslin-series/TES-034-04.webp',
          '/catalogue/teslin-series/TES-034-05.webp',
          '/catalogue/teslin-series/TES-034-06.webp',
          '/catalogue/teslin-series/TES-034-07.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Ensemble repas textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Maille textilène',
      'Design à valider',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-035',
    sku: 'TES-035',
    category: 'table',
    name: 'Ensemble repas terrasse ARDECHE - tressage noir / rouge',
    description:
      'Ensemble repas terrasse ARDECHE - tressage noir / rouge pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 140x80x74 cm, poids 18 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 140,
      w: 80,
      h: 74,
    },
    cbmPerUnit: 0.18,
    weightKg: 18,
    moqUnits: 20,
    basePriceHt: 229,
    retailPriceRef: 401,
    ecoContribution: 0.8,
    mainImageUrl: '/catalogue/teslin-series/TES-035-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-035-02.webp',
      '/catalogue/teslin-series/TES-035-03.webp',
      '/catalogue/teslin-series/TES-035-04.webp',
      '/catalogue/teslin-series/TES-035-05.webp',
      '/catalogue/teslin-series/TES-035-06.webp',
      '/catalogue/teslin-series/TES-035-07.webp',
      '/catalogue/teslin-series/TES-035-08.webp',
      '/catalogue/teslin-series/TES-035-09.webp',
      '/catalogue/teslin-series/TES-035-10.webp',
      '/catalogue/teslin-series/TES-035-11.webp',
    ],
    variants: [
      {
        id: 'tes-035-design-principal',
        name: 'tressage textilène noir / rouge',
        imageUrl: '/catalogue/teslin-series/TES-035-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-035-02.webp',
          '/catalogue/teslin-series/TES-035-03.webp',
          '/catalogue/teslin-series/TES-035-04.webp',
          '/catalogue/teslin-series/TES-035-05.webp',
          '/catalogue/teslin-series/TES-035-06.webp',
          '/catalogue/teslin-series/TES-035-07.webp',
          '/catalogue/teslin-series/TES-035-08.webp',
          '/catalogue/teslin-series/TES-035-09.webp',
          '/catalogue/teslin-series/TES-035-10.webp',
          '/catalogue/teslin-series/TES-035-11.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Ensemble repas textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Tressage textilène',
      'Coloris noir / rouge',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-036',
    sku: 'TES-036',
    category: 'table',
    name: 'Ensemble repas terrasse VERCORS - maille textilène rouge',
    description:
      'Ensemble repas terrasse VERCORS - maille textilène rouge pour terrasse de restaurant, brasserie, hôtel, camping, espace événementiel et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 140x80x74 cm, poids 18 kg. MOQ 20 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 140,
      w: 80,
      h: 74,
    },
    cbmPerUnit: 0.18,
    weightKg: 18,
    moqUnits: 20,
    basePriceHt: 229,
    retailPriceRef: 401,
    ecoContribution: 0.8,
    mainImageUrl: '/catalogue/teslin-series/TES-036-01.webp',
    galleryUrls: ['/catalogue/teslin-series/TES-036-02.webp'],
    variants: [
      {
        id: 'tes-036-design-principal',
        name: 'maille textilène rouge',
        imageUrl: '/catalogue/teslin-series/TES-036-01.webp',
        galleryUrls: ['/catalogue/teslin-series/TES-036-02.webp'],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Ensemble repas textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Maille textilène',
      'Coloris rouge',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 20 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-037',
    sku: 'TES-037',
    category: 'chair',
    name: 'Chaise de terrasse MASSIF - tressage',
    description:
      'Chaise de terrasse MASSIF - tressage pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 54x58x84 cm, poids 4.8 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 54,
      w: 58,
      h: 84,
    },
    cbmPerUnit: 0.08,
    weightKg: 4.8,
    moqUnits: 50,
    basePriceHt: 89,
    retailPriceRef: 156,
    ecoContribution: 0.3,
    mainImageUrl: '/catalogue/teslin-series/TES-037-01.webp',
    galleryUrls: [],
    variants: [
      {
        id: 'tes-037-design-principal',
        name: 'tressage textilène',
        imageUrl: '/catalogue/teslin-series/TES-037-01.webp',
        galleryUrls: [],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Tressage textilène',
      'Design à valider',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-038',
    sku: 'TES-038',
    category: 'chair',
    name: 'Chaise de terrasse OPALE - tressage',
    description:
      'Chaise de terrasse OPALE - tressage pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 54x58x84 cm, poids 4.8 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 54,
      w: 58,
      h: 84,
    },
    cbmPerUnit: 0.08,
    weightKg: 4.8,
    moqUnits: 50,
    basePriceHt: 89,
    retailPriceRef: 156,
    ecoContribution: 0.3,
    mainImageUrl: '/catalogue/teslin-series/TES-038-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-038-02.webp',
      '/catalogue/teslin-series/TES-038-03.webp',
      '/catalogue/teslin-series/TES-038-04.webp',
      '/catalogue/teslin-series/TES-038-05.webp',
      '/catalogue/teslin-series/TES-038-06.webp',
      '/catalogue/teslin-series/TES-038-07.webp',
      '/catalogue/teslin-series/TES-038-08.webp',
    ],
    variants: [
      {
        id: 'tes-038-design-principal',
        name: 'tressage textilène',
        imageUrl: '/catalogue/teslin-series/TES-038-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-038-02.webp',
          '/catalogue/teslin-series/TES-038-03.webp',
          '/catalogue/teslin-series/TES-038-04.webp',
          '/catalogue/teslin-series/TES-038-05.webp',
          '/catalogue/teslin-series/TES-038-06.webp',
          '/catalogue/teslin-series/TES-038-07.webp',
          '/catalogue/teslin-series/TES-038-08.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Tressage textilène',
      'Design à valider',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-039',
    sku: 'TES-039',
    category: 'chair',
    name: 'Chaise de terrasse IROISE - tressage',
    description:
      'Chaise de terrasse IROISE - tressage pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 54x58x84 cm, poids 4.8 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 54,
      w: 58,
      h: 84,
    },
    cbmPerUnit: 0.08,
    weightKg: 4.8,
    moqUnits: 50,
    basePriceHt: 89,
    retailPriceRef: 156,
    ecoContribution: 0.3,
    mainImageUrl: '/catalogue/teslin-series/TES-039-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-039-02.webp',
      '/catalogue/teslin-series/TES-039-03.webp',
      '/catalogue/teslin-series/TES-039-04.webp',
      '/catalogue/teslin-series/TES-039-05.webp',
      '/catalogue/teslin-series/TES-039-06.webp',
    ],
    variants: [
      {
        id: 'tes-039-design-principal',
        name: 'tressage textilène',
        imageUrl: '/catalogue/teslin-series/TES-039-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-039-02.webp',
          '/catalogue/teslin-series/TES-039-03.webp',
          '/catalogue/teslin-series/TES-039-04.webp',
          '/catalogue/teslin-series/TES-039-05.webp',
          '/catalogue/teslin-series/TES-039-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Tressage textilène',
      'Design à valider',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-040',
    sku: 'TES-040',
    category: 'chair',
    name: 'Chaise de terrasse AUBRAC - brun / rouge',
    description:
      'Chaise de terrasse AUBRAC - brun / rouge pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 54x58x84 cm, poids 4.8 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 54,
      w: 58,
      h: 84,
    },
    cbmPerUnit: 0.08,
    weightKg: 4.8,
    moqUnits: 50,
    basePriceHt: 89,
    retailPriceRef: 156,
    ecoContribution: 0.3,
    mainImageUrl: '/catalogue/teslin-series/TES-040-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-040-02.webp',
      '/catalogue/teslin-series/TES-040-03.webp',
      '/catalogue/teslin-series/TES-040-04.webp',
      '/catalogue/teslin-series/TES-040-05.webp',
      '/catalogue/teslin-series/TES-040-06.webp',
      '/catalogue/teslin-series/TES-040-07.webp',
      '/catalogue/teslin-series/TES-040-08.webp',
    ],
    variants: [
      {
        id: 'tes-040-design-principal',
        name: 'motif ondulé brun / rouge',
        imageUrl: '/catalogue/teslin-series/TES-040-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-040-02.webp',
          '/catalogue/teslin-series/TES-040-03.webp',
          '/catalogue/teslin-series/TES-040-04.webp',
          '/catalogue/teslin-series/TES-040-05.webp',
          '/catalogue/teslin-series/TES-040-06.webp',
          '/catalogue/teslin-series/TES-040-07.webp',
          '/catalogue/teslin-series/TES-040-08.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Motif ondulé',
      'Coloris brun / rouge',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-041',
    sku: 'TES-041',
    category: 'armchair',
    name: 'Fauteuil de terrasse RIVOLI - tressage',
    description:
      'Fauteuil de terrasse RIVOLI - tressage pour terrasse de restaurant, café, hôtel, rooftop et espace CHR premium. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 62x60x82 cm, poids 6.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 62,
      w: 60,
      h: 82,
    },
    cbmPerUnit: 0.1,
    weightKg: 6.2,
    moqUnits: 50,
    basePriceHt: 119,
    retailPriceRef: 208,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/teslin-series/TES-041-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-041-02.webp',
      '/catalogue/teslin-series/TES-041-03.webp',
      '/catalogue/teslin-series/TES-041-04.webp',
      '/catalogue/teslin-series/TES-041-05.webp',
      '/catalogue/teslin-series/TES-041-06.webp',
    ],
    variants: [
      {
        id: 'tes-041-design-principal',
        name: 'tressage textilène',
        imageUrl: '/catalogue/teslin-series/TES-041-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-041-02.webp',
          '/catalogue/teslin-series/TES-041-03.webp',
          '/catalogue/teslin-series/TES-041-04.webp',
          '/catalogue/teslin-series/TES-041-05.webp',
          '/catalogue/teslin-series/TES-041-06.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Fauteuil textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Tressage textilène',
      'Design à valider',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-042',
    sku: 'TES-042',
    category: 'chair',
    name: 'Chaise de terrasse MONCEAU - tressage',
    description:
      'Chaise de terrasse MONCEAU - tressage pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 54x58x84 cm, poids 4.8 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 54,
      w: 58,
      h: 84,
    },
    cbmPerUnit: 0.08,
    weightKg: 4.8,
    moqUnits: 50,
    basePriceHt: 89,
    retailPriceRef: 156,
    ecoContribution: 0.3,
    mainImageUrl: '/catalogue/teslin-series/TES-042-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-042-02.webp',
      '/catalogue/teslin-series/TES-042-03.webp',
      '/catalogue/teslin-series/TES-042-04.webp',
      '/catalogue/teslin-series/TES-042-05.webp',
      '/catalogue/teslin-series/TES-042-06.webp',
      '/catalogue/teslin-series/TES-042-07.webp',
      '/catalogue/teslin-series/TES-042-08.webp',
      '/catalogue/teslin-series/TES-042-09.webp',
      '/catalogue/teslin-series/TES-042-10.webp',
    ],
    variants: [
      {
        id: 'tes-042-design-principal',
        name: 'tressage textilène',
        imageUrl: '/catalogue/teslin-series/TES-042-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-042-02.webp',
          '/catalogue/teslin-series/TES-042-03.webp',
          '/catalogue/teslin-series/TES-042-04.webp',
          '/catalogue/teslin-series/TES-042-05.webp',
          '/catalogue/teslin-series/TES-042-06.webp',
          '/catalogue/teslin-series/TES-042-07.webp',
          '/catalogue/teslin-series/TES-042-08.webp',
          '/catalogue/teslin-series/TES-042-09.webp',
          '/catalogue/teslin-series/TES-042-10.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Tressage textilène',
      'Design à valider',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-043',
    sku: 'TES-043',
    category: 'chair',
    name: 'Chaise haute terrasse OPERA - style classique brun',
    description:
      'Chaise haute terrasse OPERA - style classique brun pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 62x60x108 cm, poids 6.2 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 62,
      w: 60,
      h: 108,
    },
    cbmPerUnit: 0.1,
    weightKg: 6.2,
    moqUnits: 50,
    basePriceHt: 119,
    retailPriceRef: 208,
    ecoContribution: 0.35,
    mainImageUrl: '/catalogue/teslin-series/TES-043-01.webp',
    galleryUrls: [
      '/catalogue/teslin-series/TES-043-02.webp',
      '/catalogue/teslin-series/TES-043-03.webp',
      '/catalogue/teslin-series/TES-043-04.webp',
      '/catalogue/teslin-series/TES-043-05.webp',
      '/catalogue/teslin-series/TES-043-06.webp',
      '/catalogue/teslin-series/TES-043-07.webp',
      '/catalogue/teslin-series/TES-043-08.webp',
    ],
    variants: [
      {
        id: 'tes-043-design-principal',
        name: 'style bistrot classique brun',
        imageUrl: '/catalogue/teslin-series/TES-043-01.webp',
        galleryUrls: [
          '/catalogue/teslin-series/TES-043-02.webp',
          '/catalogue/teslin-series/TES-043-03.webp',
          '/catalogue/teslin-series/TES-043-04.webp',
          '/catalogue/teslin-series/TES-043-05.webp',
          '/catalogue/teslin-series/TES-043-06.webp',
          '/catalogue/teslin-series/TES-043-07.webp',
          '/catalogue/teslin-series/TES-043-08.webp',
        ],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise haute textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Style bistrot classique',
      'Coloris brun',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
  {
    id: 'teslin-tes-044',
    sku: 'TES-044',
    category: 'chair',
    name: 'Chaise de terrasse BASTILLE - tressage',
    description:
      'Chaise de terrasse BASTILLE - tressage pour restaurant, café, hôtel, brasserie, camping et terrasse CHR. Mobilier extérieur professionnel en textilène outdoor et structure aluminium, dimensions 54x58x84 cm, poids 4.8 kg. MOQ 50 unités, achat groupé par container avec prix HT visible, photos produit et volume logistique. Coloris et finitions personnalisables sur projet en volume.',
    dimensions: {
      l: 54,
      w: 58,
      h: 84,
    },
    cbmPerUnit: 0.08,
    weightKg: 4.8,
    moqUnits: 50,
    basePriceHt: 89,
    retailPriceRef: 156,
    ecoContribution: 0.3,
    mainImageUrl: '/catalogue/teslin-series/TES-044-01.webp',
    galleryUrls: [],
    variants: [
      {
        id: 'tes-044-design-principal',
        name: 'tressage textilène',
        imageUrl: '/catalogue/teslin-series/TES-044-01.webp',
        galleryUrls: [],
        unitsCommitted: 0,
      },
    ],
    features: [
      'Chaise textilène',
      'Structure aluminium',
      'Assise outdoor textilène',
      'Tressage textilène',
      'Design à valider',
      'Photos groupées par fiche produit',
      'Personnalisation gros projet',
      'MOQ 50 unités',
    ],
    fireRating: 'M2',
  },
]
