// Media URLs only: no credentials, prices, availability or compatibility rules.
// Replace null with a supplied, approved URL. No image is generated by this page.
export const config = {
  catalogueHref: '/catalogue',
  // These endpoints are deliberately unconfigured. A local demo never sends data.
  // Exact token from the supplied Broadsheet design system.
  processYellow: '#edbb00',
  univers: [
    {
      url: '/home/atmospheres/salon-vue-mer.webp',
      name: 'Salon lounge sur une terrasse face à la mer',
      href: null,
    },
    {
      url: '/home/atmospheres/sieges-bleus-roses.webp',
      name: 'Fauteuils en cordage bleu et rose vus de haut',
      href: null,
    },
  ],
  parcours: [
    {
      // Photo Terrassea, prise à la réception d'un container. L'intitulé
      // décrit ce que la photo montre VRAIMENT — un dépôt, pas la terrasse
      // d'un client : même règle de preuve que le registre /livres.
      url: '/home/parcours/assises-depot-container.webp',
      name: 'Assises du catalogue déballées devant les palettes filmées, à la réception d’un container',
      href: '/catalogue',
    },
    {
      // Photo Terrassea, showroom éphémère. L'intitulé ne nomme pas de
      // revendeur : ce serait affirmer une chose que la photo ne prouve pas.
      // L'écriteau du local a été retiré au recadrage.
      url: '/home/parcours/collection-showroom.webp',
      name: 'La collection en showroom éphémère',
      href: '#contact',
    },
  ],
  // Références du catalogue : photo, nom et lien de la fiche sont résolus au
  // chargement (liveBandCards). ROP-001 (salon cordage CANNES) remplace
  // l'ancien libellé générique « Salon cordage ».
  band: [
    'BIS-020',
    'BIS-002',
    'BIS-028',
    'BIS-005',
    'ROP-003',
    'BIS-003',
    'ROP-019',
    'ROP-007',
    'ROP-001',
  ].map((name) => ({ name, url: null, href: '/catalogue' })),
  reels: [0, 1, 2, 3].map(() => ({
    url: null,
    name: null,
    href: 'https://www.instagram.com/terrassea_france',
  })),
  // Paired original photographs supplied by the catalogue owner.
  compares: [
    {
      name: 'Monceau',
      before: '/home/comparisons/monceau-noir-blanc.webp',
      after: '/home/comparisons/monceau-vert.webp',
      href: '/catalogue/#produit-BIS-002',
    },
    {
      name: 'Nice',
      before: '/home/comparisons/nice-sable.webp',
      after: '/home/comparisons/nice-terracotta.webp',
      href: '/catalogue/#produit-ROP-002',
    },
    {
      name: 'Madeleine',
      before: '/home/comparisons/madeleine-noir-blanc.webp',
      after: '/home/comparisons/madeleine-vert.webp',
      href: '/catalogue/#produit-BIS-012',
    },
  ],
  pieceChair: '/catalogue/bistro-seating-clean/BIS-012-01.webp',
  // PI-CO-014 is absent from the public library: no inferred PI-RP mapping.
  textures: {
    'PI-TR-007': '/studio/materials/pi-tr-007-detail.webp',
    'PI-CO-014': null,
    'PI-TX-021': '/studio/materials/pi-tx-021-detail.webp',
  },
  // Override a prototype photo only with its verified catalogue association.
  productPhotos: {},
}
