// Media URLs only: no credentials, prices, availability or compatibility rules.
// Replace null with a supplied, approved URL. No image is generated by this page.
export const config = {
  catalogueHref: '/catalogue',
  // These endpoints are deliberately unconfigured. A local demo never sends data.
  demo: true,
  projectEndpoint: null,
  newsletterEndpoint: null,
  // Exact token from the supplied Broadsheet design system.
  processYellow: '#edbb00',
  univers: [
    { url: null, name: 'Salon lounge, terrasse vue mer', href: null },
    { url: null, name: 'Fauteuils colorés vus de haut', href: null },
  ],
  parcours: [
    {
      url: null,
      name: 'Terrasse de restaurant équipée, service en cours',
      href: '/catalogue',
    },
    { url: null, name: 'Showroom d’un revendeur', href: '#contact' },
  ],
  band: [
    'BIS-020',
    'BIS-002',
    'BIS-028',
    'BIS-005',
    'ROP-003',
    'BIS-003',
    'ROP-019',
    'ROP-007',
    'Salon cordage',
  ].map((name) => ({ name, url: null, href: '/catalogue' })),
  reels: [0, 1, 2, 3].map(() => ({
    url: null,
    name: null,
    href: 'https://www.instagram.com/terrassea_france',
  })),
  // Exact before/after pairs must be confirmed: never replace them by unrelated models.
  compares: [
    { name: 'Fréjus', before: null, after: null },
    { name: 'Denia', before: null, after: null },
    {
      name: 'Médaillon',
      before: '/catalogue/bistro-seating-clean/BIS-012-01.webp',
      after: null,
    },
  ],
  pieceChair: '/catalogue/bistro-seating-clean/BIS-012-01.webp',
  // PI-CO-014 is absent from the public library: no inferred PI-RP mapping.
  textures: {
    'PI-TR-007': '/studio/materials/pi-tr-007-detail.webp',
    'PI-CO-014': null,
    'PI-TX-021': '/studio/materials/pi-tx-021-detail.webp',
  },
  // Override a prototype photo only with its verified catalogue association.
  productPhotos: {},
}
