/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompteRouteImport } from './routes/compte'
import { Route as CgvRouteImport } from './routes/cgv'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as IndexRouteImport } from './routes/index'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteRoute = CompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const CgvRoute = CgvRouteImport.update({
  id: '/cgv',
  path: '/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/compte': typeof CompteRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/compte': typeof CompteRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cgu': typeof CguRoute
  '/cgv': typeof CgvRoute
  '/compte': typeof CompteRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cgu'
    | '/cgv'
    | '/compte'
    | '/contact'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cgu'
    | '/cgv'
    | '/compte'
    | '/contact'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/reset-password'
  id:
    | '__root__'
    | '/'
    | '/cgu'
    | '/cgv'
    | '/compte'
    | '/contact'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CguRoute: typeof CguRoute
  CgvRoute: typeof CgvRoute
  CompteRoute: typeof CompteRoute
  ContactRoute: typeof ContactRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte': {
      id: '/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof CompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgv': {
      id: '/cgv'
      path: '/cgv'
      fullPath: '/cgv'
      preLoaderRoute: typeof CgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CguRoute: CguRoute,
  CgvRoute: CgvRoute,
  CompteRoute: CompteRoute,
  ContactRoute: ContactRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
