/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LivresRouteImport } from './routes/livres'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as ReservationIdRouteImport } from './routes/reservation/$id'
import { Route as LegalSlugRouteImport } from './routes/legal/$slug'

const LivresRoute = LivresRouteImport.update({
  id: '/livres',
  path: '/livres',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationIdRoute = ReservationIdRouteImport.update({
  id: '/reservation/$id',
  path: '/reservation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/livres': typeof LivresRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/reservation/$id': typeof ReservationIdRoute
  '/legal/': typeof LegalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/livres': typeof LivresRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/reservation/$id': typeof ReservationIdRoute
  '/legal': typeof LegalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/livres': typeof LivresRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/reservation/$id': typeof ReservationIdRoute
  '/legal/': typeof LegalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/livres' | '/legal/$slug' | '/reservation/$id' | '/legal/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/livres' | '/legal/$slug' | '/reservation/$id' | '/legal'
  id:
    | '__root__'
    | '/'
    | '/livres'
    | '/legal/$slug'
    | '/reservation/$id'
    | '/legal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LivresRoute: typeof LivresRoute
  LegalSlugRoute: typeof LegalSlugRoute
  ReservationIdRoute: typeof ReservationIdRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/livres': {
      id: '/livres'
      path: '/livres'
      fullPath: '/livres'
      preLoaderRoute: typeof LivresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation/$id': {
      id: '/reservation/$id'
      path: '/reservation/$id'
      fullPath: '/reservation/$id'
      preLoaderRoute: typeof ReservationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LivresRoute: LivresRoute,
  LegalSlugRoute: LegalSlugRoute,
  ReservationIdRoute: ReservationIdRoute,
  LegalIndexRoute: LegalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
