/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportPartenairesRouteImport } from './routes/transport-partenaires'
import { Route as StockMobilierTerrasse24hRouteImport } from './routes/stock-mobilier-terrasse-24h'
import { Route as Stock24hRouteImport } from './routes/stock-24h'
import { Route as QualiteRouteImport } from './routes/qualite'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LivresIndexRouteImport } from './routes/livres.index'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as LivresSlugRouteImport } from './routes/livres.$slug'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as CatalogueTablesRestaurantRouteImport } from './routes/catalogue.tables-restaurant'
import { Route as CatalogueChaisesRestaurantRouteImport } from './routes/catalogue.chaises-restaurant'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AccountReservationsRouteImport } from './routes/account.reservations'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as AccountReservationsReservationIdRouteImport } from './routes/account.reservations.$reservationId'

const TransportPartenairesRoute = TransportPartenairesRouteImport.update({
  id: '/transport-partenaires',
  path: '/transport-partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const StockMobilierTerrasse24hRoute =
  StockMobilierTerrasse24hRouteImport.update({
    id: '/stock-mobilier-terrasse-24h',
    path: '/stock-mobilier-terrasse-24h',
    getParentRoute: () => rootRouteImport,
  } as any)
const Stock24hRoute = Stock24hRouteImport.update({
  id: '/stock-24h',
  path: '/stock-24h',
  getParentRoute: () => rootRouteImport,
} as any)
const QualiteRoute = QualiteRouteImport.update({
  id: '/qualite',
  path: '/qualite',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LivresIndexRoute = LivresIndexRouteImport.update({
  id: '/livres/',
  path: '/livres/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const LivresSlugRoute = LivresSlugRouteImport.update({
  id: '/livres/$slug',
  path: '/livres/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueTablesRestaurantRoute =
  CatalogueTablesRestaurantRouteImport.update({
    id: '/tables-restaurant',
    path: '/tables-restaurant',
    getParentRoute: () => CatalogueRoute,
  } as any)
const CatalogueChaisesRestaurantRoute =
  CatalogueChaisesRestaurantRouteImport.update({
    id: '/chaises-restaurant',
    path: '/chaises-restaurant',
    getParentRoute: () => CatalogueRoute,
  } as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountReservationsRoute = AccountReservationsRouteImport.update({
  id: '/account/reservations',
  path: '/account/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountReservationsReservationIdRoute =
  AccountReservationsReservationIdRouteImport.update({
    id: '/$reservationId',
    path: '/$reservationId',
    getParentRoute: () => AccountReservationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalogue': typeof CatalogueRouteWithChildren
  '/faq': typeof FaqRoute
  '/qualite': typeof QualiteRoute
  '/stock-24h': typeof Stock24hRoute
  '/stock-mobilier-terrasse-24h': typeof StockMobilierTerrasse24hRoute
  '/transport-partenaires': typeof TransportPartenairesRoute
  '/account/reservations': typeof AccountReservationsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/catalogue/chaises-restaurant': typeof CatalogueChaisesRestaurantRoute
  '/catalogue/tables-restaurant': typeof CatalogueTablesRestaurantRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/livres/$slug': typeof LivresSlugRoute
  '/legal/': typeof LegalIndexRoute
  '/livres/': typeof LivresIndexRoute
  '/account/reservations/$reservationId': typeof AccountReservationsReservationIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalogue': typeof CatalogueRouteWithChildren
  '/faq': typeof FaqRoute
  '/qualite': typeof QualiteRoute
  '/stock-24h': typeof Stock24hRoute
  '/stock-mobilier-terrasse-24h': typeof StockMobilierTerrasse24hRoute
  '/transport-partenaires': typeof TransportPartenairesRoute
  '/account/reservations': typeof AccountReservationsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/catalogue/chaises-restaurant': typeof CatalogueChaisesRestaurantRoute
  '/catalogue/tables-restaurant': typeof CatalogueTablesRestaurantRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/livres/$slug': typeof LivresSlugRoute
  '/legal': typeof LegalIndexRoute
  '/livres': typeof LivresIndexRoute
  '/account/reservations/$reservationId': typeof AccountReservationsReservationIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalogue': typeof CatalogueRouteWithChildren
  '/faq': typeof FaqRoute
  '/qualite': typeof QualiteRoute
  '/stock-24h': typeof Stock24hRoute
  '/stock-mobilier-terrasse-24h': typeof StockMobilierTerrasse24hRoute
  '/transport-partenaires': typeof TransportPartenairesRoute
  '/account/reservations': typeof AccountReservationsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/catalogue/chaises-restaurant': typeof CatalogueChaisesRestaurantRoute
  '/catalogue/tables-restaurant': typeof CatalogueTablesRestaurantRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/livres/$slug': typeof LivresSlugRoute
  '/legal/': typeof LegalIndexRoute
  '/livres/': typeof LivresIndexRoute
  '/account/reservations/$reservationId': typeof AccountReservationsReservationIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalogue'
    | '/faq'
    | '/qualite'
    | '/stock-24h'
    | '/stock-mobilier-terrasse-24h'
    | '/transport-partenaires'
    | '/account/reservations'
    | '/auth/callback'
    | '/auth/login'
    | '/catalogue/chaises-restaurant'
    | '/catalogue/tables-restaurant'
    | '/legal/$slug'
    | '/livres/$slug'
    | '/legal/'
    | '/livres/'
    | '/account/reservations/$reservationId'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/catalogue'
    | '/faq'
    | '/qualite'
    | '/stock-24h'
    | '/stock-mobilier-terrasse-24h'
    | '/transport-partenaires'
    | '/account/reservations'
    | '/auth/callback'
    | '/auth/login'
    | '/catalogue/chaises-restaurant'
    | '/catalogue/tables-restaurant'
    | '/legal/$slug'
    | '/livres/$slug'
    | '/legal'
    | '/livres'
    | '/account/reservations/$reservationId'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalogue'
    | '/faq'
    | '/qualite'
    | '/stock-24h'
    | '/stock-mobilier-terrasse-24h'
    | '/transport-partenaires'
    | '/account/reservations'
    | '/auth/callback'
    | '/auth/login'
    | '/catalogue/chaises-restaurant'
    | '/catalogue/tables-restaurant'
    | '/legal/$slug'
    | '/livres/$slug'
    | '/legal/'
    | '/livres/'
    | '/account/reservations/$reservationId'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CatalogueRoute: typeof CatalogueRouteWithChildren
  FaqRoute: typeof FaqRoute
  QualiteRoute: typeof QualiteRoute
  Stock24hRoute: typeof Stock24hRoute
  StockMobilierTerrasse24hRoute: typeof StockMobilierTerrasse24hRoute
  TransportPartenairesRoute: typeof TransportPartenairesRoute
  AccountReservationsRoute: typeof AccountReservationsRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  LegalSlugRoute: typeof LegalSlugRoute
  LivresSlugRoute: typeof LivresSlugRoute
  LegalIndexRoute: typeof LegalIndexRoute
  LivresIndexRoute: typeof LivresIndexRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transport-partenaires': {
      id: '/transport-partenaires'
      path: '/transport-partenaires'
      fullPath: '/transport-partenaires'
      preLoaderRoute: typeof TransportPartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-mobilier-terrasse-24h': {
      id: '/stock-mobilier-terrasse-24h'
      path: '/stock-mobilier-terrasse-24h'
      fullPath: '/stock-mobilier-terrasse-24h'
      preLoaderRoute: typeof StockMobilierTerrasse24hRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-24h': {
      id: '/stock-24h'
      path: '/stock-24h'
      fullPath: '/stock-24h'
      preLoaderRoute: typeof Stock24hRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualite': {
      id: '/qualite'
      path: '/qualite'
      fullPath: '/qualite'
      preLoaderRoute: typeof QualiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livres/': {
      id: '/livres/'
      path: '/livres'
      fullPath: '/livres/'
      preLoaderRoute: typeof LivresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livres/$slug': {
      id: '/livres/$slug'
      path: '/livres/$slug'
      fullPath: '/livres/$slug'
      preLoaderRoute: typeof LivresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue/tables-restaurant': {
      id: '/catalogue/tables-restaurant'
      path: '/tables-restaurant'
      fullPath: '/catalogue/tables-restaurant'
      preLoaderRoute: typeof CatalogueTablesRestaurantRouteImport
      parentRoute: typeof CatalogueRoute
    }
    '/catalogue/chaises-restaurant': {
      id: '/catalogue/chaises-restaurant'
      path: '/chaises-restaurant'
      fullPath: '/catalogue/chaises-restaurant'
      preLoaderRoute: typeof CatalogueChaisesRestaurantRouteImport
      parentRoute: typeof CatalogueRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/reservations': {
      id: '/account/reservations'
      path: '/account/reservations'
      fullPath: '/account/reservations'
      preLoaderRoute: typeof AccountReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/reservations/$reservationId': {
      id: '/account/reservations/$reservationId'
      path: '/$reservationId'
      fullPath: '/account/reservations/$reservationId'
      preLoaderRoute: typeof AccountReservationsReservationIdRouteImport
      parentRoute: typeof AccountReservationsRoute
    }
  }
}

interface CatalogueRouteChildren {
  CatalogueChaisesRestaurantRoute: typeof CatalogueChaisesRestaurantRoute
  CatalogueTablesRestaurantRoute: typeof CatalogueTablesRestaurantRoute
}

const CatalogueRouteChildren: CatalogueRouteChildren = {
  CatalogueChaisesRestaurantRoute: CatalogueChaisesRestaurantRoute,
  CatalogueTablesRestaurantRoute: CatalogueTablesRestaurantRoute,
}

const CatalogueRouteWithChildren = CatalogueRoute._addFileChildren(
  CatalogueRouteChildren,
)

interface AccountReservationsRouteChildren {
  AccountReservationsReservationIdRoute: typeof AccountReservationsReservationIdRoute
}

const AccountReservationsRouteChildren: AccountReservationsRouteChildren = {
  AccountReservationsReservationIdRoute: AccountReservationsReservationIdRoute,
}

const AccountReservationsRouteWithChildren =
  AccountReservationsRoute._addFileChildren(AccountReservationsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CatalogueRoute: CatalogueRouteWithChildren,
  FaqRoute: FaqRoute,
  QualiteRoute: QualiteRoute,
  Stock24hRoute: Stock24hRoute,
  StockMobilierTerrasse24hRoute: StockMobilierTerrasse24hRoute,
  TransportPartenairesRoute: TransportPartenairesRoute,
  AccountReservationsRoute: AccountReservationsRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  LegalSlugRoute: LegalSlugRoute,
  LivresSlugRoute: LivresSlugRoute,
  LegalIndexRoute: LegalIndexRoute,
  LivresIndexRoute: LivresIndexRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
